/**
 * IFSC Data Library
 * Reads from pre-built JSON files in data/ifsc/
 * Generated by: scripts/fetch-ifsc-data.ts
 */

import fs from "fs";
import path from "path";

export interface IFSCBranch {
  ifsc: string;
  bank: string;
  bankSlug: string;
  branch: string;
  branchDisplay: string;
  city: string;
  citySlug: string;
  district: string;
  state: string;
  stateSlug: string;
  address: string;
  micr: string;
  contact: string;
  neft: boolean;
  rtgs: boolean;
  imps: boolean;
  upi: boolean;
  pageSlug: string;
}

export interface BankInfo {
  slug: string;
  name: string;
  count: number;
}

const DATA_DIR = path.join(process.cwd(), "data", "ifsc");

// In-memory cache to avoid re-reading files on every request during SSR
const cache: Record<string, IFSCBranch[]> = {};

function getBankData(bankSlug: string): IFSCBranch[] {
  if (cache[bankSlug]) return cache[bankSlug];
  const filePath = path.join(DATA_DIR, `${bankSlug}.json`);
  if (!fs.existsSync(filePath)) return [];
  const data = JSON.parse(fs.readFileSync(filePath, "utf8")) as IFSCBranch[];
  cache[bankSlug] = data;
  return data;
}

/**
 * Get all supported bank slugs
 */
export function getAllBankSlugs(): string[] {
  const banksFile = path.join(DATA_DIR, "banks.json");
  if (!fs.existsSync(banksFile)) return [];
  const banks = JSON.parse(fs.readFileSync(banksFile, "utf8")) as BankInfo[];
  return banks.map((b) => b.slug);
}

/**
 * Get all banks with metadata
 */
export function getAllBanks(): BankInfo[] {
  const banksFile = path.join(DATA_DIR, "banks.json");
  if (!fs.existsSync(banksFile)) return [];
  return JSON.parse(fs.readFileSync(banksFile, "utf8")) as BankInfo[];
}

/**
 * Get all branches for a bank
 */
export function getBranchesByBank(bankSlug: string): IFSCBranch[] {
  return getBankData(bankSlug);
}

/**
 * Get a specific branch by bank slug + page slug
 * pageSlug = branch-name-city e.g. "ramamurthy-nagar-bangalore"
 */
export function getBranchBySlug(
  bankSlug: string,
  pageSlug: string
): IFSCBranch | null {
  const branches = getBankData(bankSlug);
  return branches.find((b) => b.pageSlug === pageSlug) || null;
}

/**
 * Get branch by IFSC code
 */
export function getBranchByIFSC(ifscCode: string): IFSCBranch | null {
  // Determine bank from IFSC prefix
  const indexFile = path.join(DATA_DIR, "index.json");
  if (!fs.existsSync(indexFile)) return null;
  const index = JSON.parse(fs.readFileSync(indexFile, "utf8")) as Record<
    string,
    { bankSlug: string; pageSlug: string }
  >;
  const entry = index[ifscCode.toUpperCase()];
  if (!entry) return null;
  return getBranchBySlug(entry.bankSlug, entry.pageSlug);
}

/**
 * Get all unique cities for a bank
 */
export function getCitiesByBank(bankSlug: string): { city: string; citySlug: string; count: number }[] {
  const branches = getBankData(bankSlug);
  const cityMap: Record<string, number> = {};
  for (const b of branches) {
    const key = b.citySlug;
    cityMap[key] = (cityMap[key] || 0) + 1;
  }
  return Object.entries(cityMap)
    .map(([citySlug, count]) => {
      const branch = branches.find((b) => b.citySlug === citySlug)!;
      return { city: branch.city, citySlug, count };
    })
    .sort((a, b) => b.count - a.count); // most branches first
}

/**
 * Get branches filtered by city
 */
export function getBranchesByCity(bankSlug: string, citySlug: string): IFSCBranch[] {
  const branches = getBankData(bankSlug);
  return branches.filter((b) => b.citySlug === citySlug);
}

/**
 * Generate static params for all bank+branch combinations
 * Used in generateStaticParams() — returns top N branches for static build
 * The rest are handled by ISR (on-demand)
 *
 * NOTE: city slugs in the IFSC data are district-level names that vary by bank
 * (e.g. "bangalore-urban", "bangalore", "bengaluru" all refer to Bangalore).
 * We use substring matching to handle all variants.
 */
export function getTopBranchParams(limit = 5000): { bank: string; branch: string }[] {
  const banks = getAllBankSlugs();
  const params: { bank: string; branch: string }[] = [];

  // Priority city keywords (match any citySlug containing these substrings)
  const priorityCityKeywords = [
    "bangalore", "bengaluru",
    "mumbai", "bombay",
    "delhi",
    "chennai", "madras",
    "hyderabad",
    "kolkata", "calcutta",
    "pune",
    "ahmedabad", "ahmadabad",
    "jaipur",
    "lucknow",
    "chandigarh",
    "bhopal",
    "patna",
    "kochi", "cochin", "ernakulam",
    "indore",
    "surat",
    "nagpur",
    "visakhapatnam",
    "gurgaon", "gurugram",
    "noida",
  ];

  function isPriorityCity(citySlug: string): boolean {
    return priorityCityKeywords.some((kw) => citySlug.includes(kw));
  }

  const topBanks = ["sbi", "hdfc", "icici", "axis", "pnb", "bob", "canara", "union", "kotak"];

  for (const bankSlug of topBanks) {
    const branches = getBankData(bankSlug);
    if (!branches.length) continue;

    // First: priority cities
    const priorityBranches = branches.filter((b) => isPriorityCity(b.citySlug));
    // Then: remaining
    const remaining = branches.filter((b) => !isPriorityCity(b.citySlug));

    const ordered = [...priorityBranches, ...remaining];
    for (const b of ordered) {
      if (params.length >= limit) break;
      params.push({ bank: bankSlug, branch: b.pageSlug });
    }
  }

  // Fill remaining slots with other banks
  for (const bankSlug of banks) {
    if (topBanks.includes(bankSlug)) continue;
    const branches = getBankData(bankSlug);
    for (const b of branches) {
      if (params.length >= limit) break;
      params.push({ bank: bankSlug, branch: b.pageSlug });
    }
  }

  return params;
}

/**
 * Get all bank page params for generateStaticParams
 */
export function getAllBankParams(): { bank: string }[] {
  return getAllBankSlugs().map((slug) => ({ bank: slug }));
}

/**
 * Search branches across all banks (for search feature)
 * Searches by branch name or city
 */
export function searchBranches(query: string, bankSlug?: string, limit = 20): IFSCBranch[] {
  const q = query.toUpperCase().trim();
  if (!q) return [];

  const banks = bankSlug ? [bankSlug] : getAllBankSlugs();
  const results: IFSCBranch[] = [];

  for (const bank of banks) {
    const branches = getBankData(bank);
    for (const b of branches) {
      if (
        b.branch.includes(q) ||
        b.city.includes(q) ||
        b.ifsc.includes(q.toUpperCase())
      ) {
        results.push(b);
        if (results.length >= limit) return results;
      }
    }
  }

  return results;
}

/**
 * Get nearby branches (same city, same bank)
 */
export function getNearbyBranches(branch: IFSCBranch, limit = 5): IFSCBranch[] {
  const branches = getBranchesByCity(branch.bankSlug, branch.citySlug);
  return branches.filter((b) => b.ifsc !== branch.ifsc).slice(0, limit);
}

export const BANK_DISPLAY_NAMES: Record<string, string> = {
  sbi: "State Bank of India",
  hdfc: "HDFC Bank",
  icici: "ICICI Bank",
  axis: "Axis Bank",
  pnb: "Punjab National Bank",
  bob: "Bank of Baroda",
  canara: "Canara Bank",
  union: "Union Bank of India",
  boi: "Bank of India",
  kotak: "Kotak Mahindra Bank",
  idbi: "IDBI Bank",
  indian: "Indian Bank",
  yes: "Yes Bank",
  central: "Central Bank of India",
  indusind: "IndusInd Bank",
  federal: "Federal Bank",
  rbl: "RBL Bank",
  idfc: "IDFC FIRST Bank",
  bandhan: "Bandhan Bank",
};

export const BANK_OFFICIAL_URLS: Record<string, string> = {
  sbi: "https://www.sbi.co.in",
  hdfc: "https://www.hdfcbank.com",
  icici: "https://www.icicibank.com",
  axis: "https://www.axisbank.com",
  pnb: "https://www.pnbindia.in",
  bob: "https://www.bankofbaroda.in",
  canara: "https://canarabank.com",
  union: "https://www.unionbankofindia.co.in",
  boi: "https://www.bankofindia.co.in",
  kotak: "https://www.kotak.com",
  idbi: "https://www.idbibank.in",
  indian: "https://www.indianbank.in",
  yes: "https://www.yesbank.in",
  central: "https://www.centralbankofindia.co.in",
  indusind: "https://www.indusind.com",
  federal: "https://www.federalbank.co.in",
  rbl: "https://www.rblbank.com",
  idfc: "https://www.idfcfirstbank.com",
  bandhan: "https://www.bandhanbank.com",
};

export const BANK_IFSC_PREFIX: Record<string, string> = {
  sbi: "SBIN",
  hdfc: "HDFC",
  icici: "ICIC",
  axis: "UTIB",
  pnb: "PUNB",
  bob: "BARB",
  canara: "CNRB",
  union: "UBIN",
  boi: "BKID",
  kotak: "KKBK",
  idbi: "IBKL",
  indian: "IDIB",
  yes: "YESB",
  central: "CBIN",
  indusind: "INDB",
  federal: "FDRL",
  rbl: "RATN",
  idfc: "IDFB",
  bandhan: "BDBL",
};
