/**
 * Pincode Data Library
 * Reads from pre-built JSON files in data/pincode/
 * Generated by: scripts/process-pincode-data.ts
 */

import fs from "fs";
import path from "path";

export interface PincodeRecord {
  pincode: string;
  places: string[];
  postOffice: string;
  district: string;
  districtSlug: string;
  state: string;
  stateSlug: string;
  taluk: string;
  lat: string;
  lng: string;
}

export interface PincodeSummary {
  pincode: string;
  postOffice: string;
  district: string;
  state: string;
  stateSlug: string;
}

const DATA_DIR = path.join(process.cwd(), "data", "pincode");
const cache: Record<string, PincodeRecord[]> = {};

function getStateData(stateSlug: string): PincodeRecord[] {
  if (cache[stateSlug]) return cache[stateSlug];
  const file = path.join(DATA_DIR, `${stateSlug}.json`);
  if (!fs.existsSync(file)) return [];
  const data = JSON.parse(fs.readFileSync(file, "utf8")) as PincodeRecord[];
  cache[stateSlug] = data;
  return data;
}

function getIndex(): Record<string, PincodeSummary> {
  const file = path.join(DATA_DIR, "index.json");
  if (!fs.existsSync(file)) return {};
  return JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, PincodeSummary>;
}

/**
 * Look up a pincode — returns full record or null
 */
export function getPincodeData(pincode: string): PincodeRecord | null {
  const index = getIndex();
  const summary = index[pincode];
  if (!summary) return null;

  const stateData = getStateData(summary.stateSlug);
  return stateData.find((r) => r.pincode === pincode) || null;
}

/**
 * Get all pincodes for a state (for generateStaticParams)
 */
export function getPincodesByState(stateSlug: string): PincodeRecord[] {
  return getStateData(stateSlug);
}

/**
 * Get all state slugs
 */
export function getAllStatesSlugs(): string[] {
  const file = path.join(DATA_DIR, "states.json");
  if (!fs.existsSync(file)) return [];
  const states = JSON.parse(fs.readFileSync(file, "utf8")) as { slug: string }[];
  return states.map((s) => s.slug);
}

/**
 * Get all pincode params for generateStaticParams — top states first
 */
export function getAllPincodeParams(): { pincode: string }[] {
  const index = getIndex();
  return Object.keys(index).map((p) => ({ pincode: p }));
}

/**
 * Get nearby pincodes (same district)
 */
export function getNearbyPincodes(record: PincodeRecord, limit = 8): PincodeRecord[] {
  const stateData = getStateData(record.stateSlug);
  return stateData
    .filter((r) => r.districtSlug === record.districtSlug && r.pincode !== record.pincode)
    .slice(0, limit);
}

/**
 * Search pincodes by place name or district (for API route)
 */
export function searchPincodes(query: string, limit = 10): PincodeSummary[] {
  const q = query.toLowerCase().trim();
  if (!q || q.length < 3) return [];

  const index = getIndex();
  const results: PincodeSummary[] = [];

  for (const summary of Object.values(index)) {
    if (
      summary.postOffice.toLowerCase().includes(q) ||
      summary.district.toLowerCase().includes(q) ||
      summary.pincode.startsWith(q)
    ) {
      results.push(summary);
      if (results.length >= limit) break;
    }
  }
  return results;
}
