/**
 * Pincode Data Library
 * Reads from pre-built JSON files in data/pincode/
 * Generated by: scripts/process-pincode-data.ts
 *
 * URL structure: /pincode/[stateSlug]/[districtSlug]/[postOffice-slug]-[pincode]
 * e.g.  /pincode/karnataka/bengaluru/banaswadi-560043
 */

import fs from "fs";
import path from "path";

export interface PincodeRecord {
  pincode: string;
  places: string[];
  postOffice: string;
  district: string;
  districtSlug: string;
  state: string;
  stateSlug: string;
  taluk: string;
  lat: string;
  lng: string;
}

export interface PincodeSummary {
  pincode: string;
  postOffice: string;
  district: string;
  districtSlug: string;
  state: string;
  stateSlug: string;
}

export interface StateEntry {
  slug: string;
  name: string;
  count: number;
}

const DATA_DIR = path.join(process.cwd(), "data", "pincode");
const stateCache: Record<string, PincodeRecord[]> = {};
let _index: Record<string, PincodeSummary> | null = null;
let _states: StateEntry[] | null = null;

// ─── slugify ─────────────────────────────────────────────────────────────────

export function slugifyText(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

/** "Banaswadi" + "560043" → "banaswadi-560043" */
export function getPincodeSlug(record: Pick<PincodeRecord, "postOffice" | "pincode">): string {
  return slugifyText(record.postOffice) + "-" + record.pincode;
}

// ─── loaders ─────────────────────────────────────────────────────────────────

function getIndex(): Record<string, PincodeSummary> {
  if (!_index) {
    const file = path.join(DATA_DIR, "index.json");
    _index = JSON.parse(fs.readFileSync(file, "utf-8")) as Record<string, PincodeSummary>;
  }
  return _index!;
}

function getStateData(stateSlug: string): PincodeRecord[] {
  if (stateCache[stateSlug]) return stateCache[stateSlug];
  const file = path.join(DATA_DIR, `${stateSlug}.json`);
  if (!fs.existsSync(file)) return [];
  stateCache[stateSlug] = JSON.parse(fs.readFileSync(file, "utf-8")) as PincodeRecord[];
  return stateCache[stateSlug];
}

function getStatesList(): StateEntry[] {
  if (!_states) {
    const file = path.join(DATA_DIR, "states.json");
    _states = JSON.parse(fs.readFileSync(file, "utf-8")) as StateEntry[];
  }
  return _states!;
}

// ─── lookups ─────────────────────────────────────────────────────────────────

/** Look up by 6-digit pincode number */
export function getPincodeData(pincode: string): PincodeRecord | null {
  const idx = getIndex();
  const summary = idx[pincode];
  if (!summary) return null;
  const data = getStateData(summary.stateSlug);
  return data.find((r) => r.pincode === pincode) ?? null;
}

/**
 * Look up by hierarchical slug params.
 * Extracts pincode from the last 6 chars of slug for O(n) scan.
 */
export function getPincodeBySlug(
  stateSlug: string,
  districtSlug: string,
  slug: string
): PincodeRecord | null {
  // slug = "banaswadi-560043" — pincode is always the last 6 chars
  const pincode = slug.slice(-6);
  if (!/^\d{6}$/.test(pincode)) return null;
  const data = getStateData(stateSlug);
  return (
    data.find(
      (r) => r.pincode === pincode && r.districtSlug === districtSlug
    ) ?? null
  );
}

/** Get the full hierarchical URL path for a record */
export function getPincodePath(record: Pick<PincodeRecord, "stateSlug" | "districtSlug" | "postOffice" | "pincode">): string {
  return `/pincode/${record.stateSlug}/${record.districtSlug}/${getPincodeSlug(record)}`;
}

/** Given a raw pincode number, get its canonical URL */
export function getPincodeCanonicalUrl(pincode: string): string | null {
  const idx = getIndex();
  const s = idx[pincode];
  if (!s) return null;
  const slug = slugifyText(s.postOffice) + "-" + pincode;
  return `/pincode/${s.stateSlug}/${s.districtSlug}/${slug}`;
}

// ─── state / district helpers ─────────────────────────────────────────────────

export interface DistrictEntry {
  districtSlug: string;
  district: string;
  count: number;
}

/** All districts in a state with pincode counts */
export function getDistrictsByState(stateSlug: string): DistrictEntry[] {
  const data = getStateData(stateSlug);
  const map: Record<string, DistrictEntry> = {};
  for (const r of data) {
    if (!map[r.districtSlug]) {
      map[r.districtSlug] = { districtSlug: r.districtSlug, district: r.district, count: 0 };
    }
    map[r.districtSlug].count++;
  }
  return Object.values(map).sort((a, b) => a.district.localeCompare(b.district));
}

/** All pincodes in a district */
export function getPincodesByDistrict(stateSlug: string, districtSlug: string): PincodeRecord[] {
  return getStateData(stateSlug)
    .filter((r) => r.districtSlug === districtSlug)
    .sort((a, b) => a.pincode.localeCompare(b.pincode));
}

/** All states with pincode count */
export function getAllStatesWithCounts(): { stateSlug: string; state: string; count: number }[] {
  return getStatesList().map((s) => ({
    stateSlug: s.slug,
    state: s.name,
    count: s.count,
  })).sort((a, b) => a.state.localeCompare(b.state));
}

/** State name from slug */
export function getStateName(stateSlug: string): string {
  const data = getStateData(stateSlug);
  return data[0]?.state ?? stateSlug;
}

// ─── generateStaticParams helpers ────────────────────────────────────────────

/** For /pincode/[state] */
export function getAllStateParams(): { state: string }[] {
  return getStatesList().map((s) => ({ state: s.slug }));
}

/** For /pincode/[state]/[district] */
export function getAllDistrictParams(): { state: string; district: string }[] {
  const states = getStatesList();
  const out: { state: string; district: string }[] = [];
  for (const s of states) {
    const districts = getDistrictsByState(s.slug);
    for (const d of districts) {
      out.push({ state: s.slug, district: d.districtSlug });
    }
  }
  return out;
}

/** For /pincode/[state]/[district]/[slug] */
export function getAllPincodeParams(): { pincode: string }[] {
  const idx = getIndex();
  return Object.keys(idx).map((p) => ({ pincode: p }));
}

/** New 3-level params for the new route */
export function getAllPincodeSlugParams(): { state: string; district: string; slug: string }[] {
  const states = getStatesList();
  const out: { state: string; district: string; slug: string }[] = [];
  for (const s of states) {
    const data = getStateData(s.slug);
    for (const r of data) {
      out.push({
        state: r.stateSlug,
        district: r.districtSlug,
        slug: getPincodeSlug(r),
      });
    }
  }
  return out;
}

// ─── nearby ──────────────────────────────────────────────────────────────────

export function getNearbyPincodes(record: PincodeRecord, limit = 8): PincodeRecord[] {
  return getStateData(record.stateSlug)
    .filter((r) => r.districtSlug === record.districtSlug && r.pincode !== record.pincode)
    .slice(0, limit);
}

// ─── search ──────────────────────────────────────────────────────────────────

export function searchPincodes(query: string, limit = 10): PincodeSummary[] {
  const q = query.toLowerCase().trim();
  if (!q || q.length < 3) return [];
  const idx = getIndex();
  const results: PincodeSummary[] = [];
  for (const summary of Object.values(idx)) {
    if (
      summary.postOffice.toLowerCase().includes(q) ||
      summary.district.toLowerCase().includes(q) ||
      summary.pincode.startsWith(q)
    ) {
      results.push(summary);
      if (results.length >= limit) break;
    }
  }
  return results;
}
