#!/usr/bin/env python3
"""Batch 4: Rajasthan, Haryana, Delhi, Uttarakhand, Jharkhand, Chhattisgarh, Punjab"""
import json, pathlib

f = pathlib.Path("agents/scheme-pipeline-list.json")
d = json.loads(f.read_text())

new_schemes = [
  # ─── RAJASTHAN ────────────────────────────────────────────────────
  {"name":"Mukhyamantri Chiranjeevi Swasthya Bima","state":"Rajasthan","category":"Health",
   "slug":"mukhyamantri-chiranjeevi-swasthya-bima-rajasthan","officialUrl":"https://chiranjeevi.rajasthan.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mcsby","priority":1,
   "estimatedMonthlySearches":200000,"langs":["en","hi"],
   "notes":"₹25 lakh health insurance per family per year in Rajasthan. Universal — all resident families eligible."},
  {"name":"Mukhyamantri Anuprati Coaching Yojana","state":"Rajasthan","category":"Education",
   "slug":"mukhyamantri-anuprati-coaching-yojana-rajasthan","officialUrl":"https://sje.rajasthan.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/maacy","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"Free coaching for UPSC/RPSC/SSC/bank exams for SC/ST/OBC/EWS students in Rajasthan."},
  {"name":"Rajasthan Palanhar Yojana","state":"Rajasthan","category":"Social Welfare",
   "slug":"rajasthan-palanhar-yojana-orphan-children","officialUrl":"https://sje.rajasthan.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rjspy","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"₹1,500/month for caretakers of orphans/destitute children. 0-5 years: ₹1,500; 6-18: ₹2,500."},
  {"name":"Ambedkar DBT Voucher Scheme Rajasthan","state":"Rajasthan","category":"Education",
   "slug":"ambedkar-dbt-voucher-scheme-rajasthan-rent","officialUrl":"https://sje.rajasthan.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/advsr","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹2,000/month rent + electricity voucher for SC/ST/OBC/EWS students away from home for study."},
  {"name":"Rajasthan Mukhyamantri Vishwakarma Pension","state":"Rajasthan","category":"Social Welfare",
   "slug":"rajasthan-vishwakarma-pension-artisan","officialUrl":"https://ssp.rajasthan.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rjvps","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹2,000/month pension for artisans and craftsmen (Vishwakarma community) in Rajasthan."},
  {"name":"Rajasthan Mukhyamantri Bal Gopal Yojana","state":"Rajasthan","category":"Education",
   "slug":"rajasthan-bal-gopal-yojana-milk-students","officialUrl":"https://rajshaladarpan.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rjbgy","priority":3,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Free milk (200ml) on school days for government school children Class 1-8 in Rajasthan."},
  {"name":"Rajasthan Old Age Pension Vridhjan Samman","state":"Rajasthan","category":"Social Welfare",
   "slug":"rajasthan-vridhjan-samman-pension-apply","officialUrl":"https://ssp.rajasthan.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rjvsp","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"₹1,000-1,500/month old age pension in Rajasthan. Apply at ssp.rajasthan.gov.in."},
  {"name":"Rajasthan Widow Pension Ekl Nari","state":"Rajasthan","category":"Social Welfare",
   "slug":"rajasthan-ekl-nari-widow-pension","officialUrl":"https://ssp.rajasthan.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rjenps","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"₹1,000-1,500/month widow/single woman pension in Rajasthan. ssp.rajasthan.gov.in"},
  {"name":"Mukhyamantri Digital Seva Yojana Rajasthan","state":"Rajasthan","category":"Women & Family",
   "slug":"mukhyamantri-digital-seva-yojana-free-smartphone","officialUrl":"https://jansoochna.rajasthan.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mdsyr","priority":2,
   "estimatedMonthlySearches":150000,"langs":["en","hi"],
   "notes":"Free smartphone with 3 years data for women household heads in Rajasthan."},

  # ─── HARYANA ──────────────────────────────────────────────────────
  {"name":"Mukhyamantri Parivar Samridhi Yojana Haryana","state":"Haryana","category":"Social Welfare",
   "slug":"mukhyamantri-parivar-samridhi-yojana-haryana","officialUrl":"https://cm-psy.haryana.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hmpsy","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"₹6,000/year social security to economically weak families in Haryana. Multiple benefit types."},
  {"name":"Haryana Saksham Yuva Scheme","state":"Haryana","category":"Employment",
   "slug":"haryana-saksham-yuva-unemployment-allowance","officialUrl":"https://hreyahs.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hsys","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"₹900-3,000/month unemployment allowance for Haryana graduates. Plus honorarium for work assignments."},
  {"name":"Meri Fasal Mera Byora Haryana","state":"Haryana","category":"Agriculture",
   "slug":"meri-fasal-mera-byora-haryana-crop-registration","officialUrl":"https://fasal.haryana.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hmfmb","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"Crop registration portal in Haryana. Mandatory for MSP procurement, insurance, and all crop benefits."},
  {"name":"Haryana Mahila Samridhi Yojana","state":"Haryana","category":"Women & Family",
   "slug":"haryana-mahila-samridhi-yojana-women-loan","officialUrl":"https://haryanascbc.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hmsy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹60,000 loan at 5% interest for SC women entrepreneurs in Haryana. HBSC administered."},
  {"name":"Haryana CM Antyodaya Parivar Utthan Yojana","state":"Haryana","category":"Social Welfare",
   "slug":"haryana-antyodaya-parivar-utthan-yojana","officialUrl":"https://parivarutthan.haryana.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hapy","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"Skill and livelihood support for families with income <₹1 lakh/year. 1.8 lakh families identified."},
  {"name":"Haryana Kisan Mitra Yojana","state":"Haryana","category":"Agriculture",
   "slug":"haryana-kisan-mitra-yojana-small-farmers","officialUrl":"https://agriharyana.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hkmy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Package of benefits for small/marginal farmers in Haryana — insurance, pension, soil testing."},
  {"name":"Haryana Old Age Samman Allowance","state":"Haryana","category":"Social Welfare",
   "slug":"haryana-old-age-samman-allowance-pension","officialUrl":"https://socialjusticehry.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hoasa","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"₹3,000/month old age pension for 60+ in Haryana. Apply at socialjusticehry.gov.in."},
  {"name":"Haryana Disability Pension","state":"Haryana","category":"Social Welfare",
   "slug":"haryana-disability-pension-divyang","officialUrl":"https://socialjusticehry.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hdp","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹3,000/month disability pension for persons with 70%+ disability in Haryana."},
  {"name":"Haryana Free Bijli 2000 Units","state":"Haryana","category":"Energy",
   "slug":"haryana-free-electricity-2000-units-bpl","officialUrl":"https://dhbvn.org.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/hfbu","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"BPL households in Haryana get 100 units free per month. Rs 2 per unit for next 100 units."},

  # ─── DELHI ────────────────────────────────────────────────────────
  {"name":"Mukhyamantri Mahila Samman Yojana Delhi","state":"Delhi","category":"Women & Family",
   "slug":"mukhyamantri-mahila-samman-yojana-delhi","officialUrl":"https://delhi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/dmmsy","priority":1,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"₹1,000/month to women 18+ in Delhi. Apply via Aam Aadmi Party app/portal. High search volume."},
  {"name":"Delhi Free Electricity 200 Units","state":"Delhi","category":"Energy",
   "slug":"delhi-free-electricity-200-units-scheme","officialUrl":"https://bsesdelhi.com",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/dfes","priority":2,
   "estimatedMonthlySearches":150000,"langs":["en","hi"],
   "notes":"200 units free electricity per month for Delhi residents. Above 200 units billed normally."},
  {"name":"Delhi Aam Aadmi Clinic","state":"Delhi","category":"Health",
   "slug":"delhi-aam-aadmi-clinic-mohalla-clinic","officialUrl":"https://mohallaclinic.delhi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/daac","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Free OPD, 212 diagnostic tests, 50+ medicines. 500+ clinics across Delhi."},
  {"name":"Delhi Rozgar Bazaar Portal","state":"Delhi","category":"Labour & Employment",
   "slug":"delhi-rozgar-bazaar-job-portal","officialUrl":"https://jobs.delhi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/drbp","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"Free job portal for Delhi job seekers. Matches candidates with employer vacancies."},
  {"name":"Delhi Construction Worker Welfare Scheme","state":"Delhi","category":"Labour & Employment",
   "slug":"delhi-construction-worker-welfare-scheme","officialUrl":"https://bocw.delhi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/dcwws","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Scholarship, accident benefit, maternity, pension for registered construction workers in Delhi."},
  {"name":"Delhi EV Policy Subsidy","state":"Delhi","category":"Energy",
   "slug":"delhi-ev-policy-electric-vehicle-subsidy","officialUrl":"https://ev.delhi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/devp","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"₹5,000-30,000 subsidy on buying e-scooter/e-cycle/e-auto in Delhi. Switch Delhi scheme."},

  # ─── UTTARAKHAND ──────────────────────────────────────────────────
  {"name":"Mukhyamantri Swarojgar Yojana Uttarakhand","state":"Uttarakhand","category":"Business & Finance",
   "slug":"mukhyamantri-swarojgar-yojana-uttarakhand","officialUrl":"https://msy.uk.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ukmsy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Loan ₹25,000-2 lakh for new micro enterprise in Uttarakhand. 25% subsidy for hills. msy.uk.gov.in"},
  {"name":"Mukhyamantri Vatsalya Yojana Uttarakhand","state":"Uttarakhand","category":"Women & Family",
   "slug":"mukhyamantri-vatsalya-yojana-uttarakhand","officialUrl":"https://escholarship.uk.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ukvvy","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"₹3,000/month to mothers who give up jobs to raise children under 3. COVID orphan support also."},
  {"name":"Uttarakhand Mukhyamantri Mahila Poshan Yojana","state":"Uttarakhand","category":"Health",
   "slug":"uttarakhand-mahila-poshan-yojana-nutrition","officialUrl":"https://icds.uk.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ukmmpy","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"Free nutrition supplements (sattu, pulses, oil) for pregnant and lactating women in Uttarakhand."},
  {"name":"Uttarakhand Old Age Pension","state":"Uttarakhand","category":"Social Welfare",
   "slug":"uttarakhand-old-age-pension-apply","officialUrl":"https://ssp.uk.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ukoap","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹1,200/month for seniors 60+ in Uttarakhand. Apply online at ssp.uk.gov.in."},
  {"name":"Mukhyamantri Ekl Mahila Swarojgar Yojana","state":"Uttarakhand","category":"Women & Family",
   "slug":"mukhyamantri-ekl-mahila-swarojgar-uttarakhand","officialUrl":"https://swrojgar.uk.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ukemsy","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"Interest-free loan up to ₹1 lakh for single/widow/divorced women entrepreneurs in Uttarakhand."},

  # ─── JHARKHAND (additions) ────────────────────────────────────────
  {"name":"Jharkhand Mukhyamantri Sathi Yojana","state":"Jharkhand","category":"Social Welfare",
   "slug":"jharkhand-mukhyamantri-sathi-yojana","officialUrl":"https://jharkhand.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/jhmsy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹5,000/month for critically ill patients' family members to stay with them at hospital."},
  {"name":"Jharkhand Guruji Credit Card","state":"Jharkhand","category":"Education",
   "slug":"jharkhand-guruji-credit-card-education-loan","officialUrl":"https://jharkhand.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/jhgcc","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹10 lakh education loan for higher studies for Jharkhand students. 0% interest for girls."},
  {"name":"Jharkhand Savitribai Phule Kishori Samridhi","state":"Jharkhand","category":"Women & Family",
   "slug":"jharkhand-savitribai-phule-kishori-samridhi","officialUrl":"https://jharkhand.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/jhspksy","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"₹40,000 in installments from Class 8 to 18 years for adolescent girls in Jharkhand."},
  {"name":"Jharkhand Mukhyamantri Maiya Samman Yojana","state":"Jharkhand","category":"Women & Family",
   "slug":"jharkhand-maiya-samman-yojana-women-monthly","officialUrl":"https://maiyasamman.jharkhand.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/jhmmsmy","priority":1,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"₹2,500/month to women 18-50 in Jharkhand. 3 months retrospective payment to new beneficiaries."},

  # ─── CHHATTISGARH (additions) ─────────────────────────────────────
  {"name":"Rajiv Gandhi Grameen Bhoomihin Mazdoor Nyay Yojana","state":"Chhattisgarh","category":"Agriculture",
   "slug":"rajiv-gandhi-bhoomihin-mazdoor-nyay-chhattisgarh","officialUrl":"https://rgbmnyk.cg.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rgbmny","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹7,000/year for landless agricultural labourers in Chhattisgarh. 3.5 lakh beneficiaries."},
  {"name":"CG Mukhyamantri Kisan Mitan Yojana","state":"Chhattisgarh","category":"Agriculture",
   "slug":"cg-kisan-mitan-yojana-agri-service-centre","officialUrl":"https://agri.cg.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/cgkmmy","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Farm service centres run by trained youth. Subsidised machinery rental and agri-input supply in CG."},
  {"name":"CG Mukhyamantri Suposhan Abhiyan","state":"Chhattisgarh","category":"Health",
   "slug":"cg-mukhyamantri-suposhan-abhiyan-malnutrition","officialUrl":"https://cgwcd.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/cgmsa","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"Door-to-door nutrition monitoring + hot meals for malnourished children in Chhattisgarh."},

  # ─── PUNJAB ────────────────────────────────────────────────────────
  {"name":"Atta Dal Scheme Punjab","state":"Punjab","category":"Social Welfare",
   "slug":"atta-dal-scheme-punjab-free-ration","officialUrl":"https://punjab.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pjads","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"5 kg atta + 1 kg dal free per person per month for BPL/BPL-SC families in Punjab."},
  {"name":"Bhagwant Mann Sarkar Di Guarantee Aam Aadmi Clinic","state":"Punjab","category":"Health",
   "slug":"aam-aadmi-clinic-punjab-free-health","officialUrl":"https://aadaab.punjab.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pjaac","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en"],
   "notes":"Free OPD, 38 diagnostic tests, medicines at 800+ Aam Aadmi Clinics in Punjab."},
  {"name":"Punjab Ghar Ghar Rozgar","state":"Punjab","category":"Labour & Employment",
   "slug":"punjab-ghar-ghar-rozgar-employment-portal","officialUrl":"https://pgrkam.com",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pjggr","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en"],
   "notes":"Punjab job portal for skilled and unskilled workers. pgrkam.com links job seekers with employers."},
  {"name":"Punjab Mata Kanya Scheme","state":"Punjab","category":"Women & Family",
   "slug":"punjab-mata-kanya-baal-sahyogi-girl-child","officialUrl":"https://swc.punjab.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pjmks","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en"],
   "notes":"₹51,000 FD at birth for BPL girls in Punjab. Matured at 18 for education/marriage."},
  {"name":"Punjab Post Matric Scholarship SC Students","state":"Punjab","category":"Education",
   "slug":"punjab-post-matric-scholarship-sc-apply","officialUrl":"https://punjabscholarships.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pjpms","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"Post-matric scholarship for SC students in Punjab. Apply at punjabscholarships.gov.in."},
  {"name":"Punjab Mukhyamantri Solar Pump Yojana","state":"Punjab","category":"Agriculture",
   "slug":"punjab-mukhyamantri-solar-pump-yojana-farmers","officialUrl":"https://peda.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pjmspy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"50-90% subsidy on solar pump sets for Punjab farmers. Up to 10 HP capacity."},
  {"name":"Punjab Ashirwad Scheme","state":"Punjab","category":"Women & Family",
   "slug":"punjab-ashirwad-scheme-marriage-grant-bpl","officialUrl":"https://punjab.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pjas","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en"],
   "notes":"₹51,000 marriage grant for BPL/SC girls in Punjab. Applied before marriage ceremony."},
]

existing = {s["slug"] for s in d["schemes"]}
added = [s for s in new_schemes if s["slug"] not in existing]
d["schemes"].extend(added)
f.write_text(json.dumps(d, indent=2, ensure_ascii=False))
print(f"Added {len(added)} schemes. Total: {len(d['schemes'])}")
