#!/usr/bin/env python3
"""Batch 1: Central schemes — Agriculture (15), Health (15), Education (12), Misc (8)"""
import json, pathlib

f = pathlib.Path("agents/scheme-pipeline-list.json")
d = json.loads(f.read_text())
existing_slugs = {s["slug"] for s in d["schemes"]}

new_schemes = [
  # ─── AGRICULTURE ──────────────────────────────────────────────────
  {"name":"PM Kisan Maan Dhan Yojana","state":"Central","category":"Agriculture",
   "slug":"pm-kisan-maan-dhan-yojana-farmer-pension","officialUrl":"https://maandhan.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmkmy","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹3,000/month pension for small/marginal farmers after age 60. Register via CSC."},
  {"name":"Paramparagat Krishi Vikas Yojana","state":"Central","category":"Agriculture",
   "slug":"paramparagat-krishi-vikas-yojana-organic-farming","officialUrl":"https://pgsindia-ncof.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pkvy","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"₹50,000/ha over 3 years for organic farming clusters. PGS certification."},
  {"name":"PM Krishi Sinchayee Yojana","state":"Central","category":"Agriculture",
   "slug":"pm-krishi-sinchayee-yojana-drip-irrigation","officialUrl":"https://pmksy.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmksy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Drip/sprinkler irrigation subsidy. Har Khet Ko Paani. More Crop Per Drop."},
  {"name":"PM Kusum Yojana","state":"Central","category":"Agriculture",
   "slug":"pm-kusum-yojana-solar-pump-farmers","officialUrl":"https://mnre.gov.in/solar/schemes",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmkusum","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"Solar pump subsidy for farmers. Component A: solar plant; B: standalone pump; C: solarize grid pumps."},
  {"name":"Soil Health Card Scheme","state":"Central","category":"Agriculture",
   "slug":"soil-health-card-scheme-apply","officialUrl":"https://soilhealth.dac.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/shcs","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Free soil testing and Soil Health Card for farmers with nutrient recommendations."},
  {"name":"PM Matsya Sampada Yojana","state":"Central","category":"Agriculture",
   "slug":"pm-matsya-sampada-yojana-fisheries","officialUrl":"https://pmmsy.dof.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmmsy","priority":2,
   "estimatedMonthlySearches":25000,"langs":["en","hi"],
   "notes":"₹20,050 crore for fisheries infra. Subsidies for fish farming, boats, cold chains."},
  {"name":"National Horticulture Mission","state":"Central","category":"Agriculture",
   "slug":"national-horticulture-mission-subsidy","officialUrl":"https://midh.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nhm","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Subsidy on fruit/vegetable/flower/spice cultivation, cold storage, pack houses."},
  {"name":"PM FME Scheme","state":"Central","category":"Agriculture",
   "slug":"pm-fme-micro-food-processing-scheme","officialUrl":"https://mofpi.gov.in/pmfme",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmfme","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Up to ₹10 lakh credit-linked subsidy for micro food processing units. FPOs, SHGs, co-ops."},
  {"name":"Agriculture Infrastructure Fund","state":"Central","category":"Agriculture",
   "slug":"agriculture-infrastructure-fund-aif-loan","officialUrl":"https://agriinfra.dac.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/aif","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"3% interest subsidy on loans up to ₹2 crore for post-harvest infra (cold storage, silos, grading)."},
  {"name":"National Livestock Mission","state":"Central","category":"Agriculture",
   "slug":"national-livestock-mission-animal-husbandry","officialUrl":"https://nlm.udyamimitra.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nlm","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"Subsidy for goat, pig, poultry units. Breed improvement. Fodder development."},
  {"name":"Rashtriya Gokul Mission","state":"Central","category":"Agriculture",
   "slug":"rashtriya-gokul-mission-cow-breed","officialUrl":"https://dahd.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rgm","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Breed improvement for indigenous cattle and buffalo. Gokul Grams, Kamdhenu Sankrit."},
  {"name":"PM AASHA Scheme","state":"Central","category":"Agriculture",
   "slug":"pm-aasha-msp-price-support-farmers","officialUrl":"https://pmaasha.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmaasha","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"MSP price support for oilseeds and pulses. Price Deficiency Payment Scheme (PDPS)."},
  {"name":"National Beekeeping and Honey Mission","state":"Central","category":"Agriculture",
   "slug":"national-beekeeping-honey-mission-nbhm","officialUrl":"https://midh.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nbhm","priority":3,
   "estimatedMonthlySearches":8000,"langs":["en","hi"],
   "notes":"Subsidy on bee boxes, honey extraction, training for beekeepers."},
  {"name":"Gramin Bhandaran Yojana","state":"Central","category":"Agriculture",
   "slug":"gramin-bhandaran-yojana-rural-storage","officialUrl":"https://nabard.org",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/gby","priority":3,
   "estimatedMonthlySearches":8000,"langs":["en","hi"],
   "notes":"Capital subsidy for rural godown/warehouse construction. 25-33.33% subsidy via NABARD."},
  {"name":"National Mission on Edible Oils – Oil Palm","state":"Central","category":"Agriculture",
   "slug":"national-mission-edible-oils-oil-palm","officialUrl":"https://nmeo-op.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nmeo","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"Price assurance + subsidy for oil palm cultivation in NE India, Andaman, tribal areas."},

  # ─── HEALTH ───────────────────────────────────────────────────────
  {"name":"Janani Suraksha Yojana","state":"Central","category":"Health",
   "slug":"janani-suraksha-yojana-delivery-cash","officialUrl":"https://nhm.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/jsy","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"₹1,400 (rural) / ₹1,000 (urban) cash to BPL women for institutional delivery."},
  {"name":"Pradhan Mantri Matru Vandana Yojana","state":"Central","category":"Health",
   "slug":"pm-matru-vandana-yojana-pmmvy-apply","officialUrl":"https://wcd.nic.in/pmmvy",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmmvy","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹5,000 in 3 installments to pregnant and lactating mothers for first live birth."},
  {"name":"Mission Indradhanush","state":"Central","category":"Health",
   "slug":"mission-indradhanush-vaccination-children","officialUrl":"https://nhm.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mi","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Full vaccination for children under 2 and pregnant women. 12 vaccine-preventable diseases."},
  {"name":"Nikshay Poshan Yojana","state":"Central","category":"Health",
   "slug":"nikshay-poshan-yojana-tb-patient-500","officialUrl":"https://nikshay.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/npy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹500/month nutritional support for TB patients till treatment completion. DBT to bank."},
  {"name":"Janaushadhi Scheme","state":"Central","category":"Health",
   "slug":"pm-janaushadhi-pariyojana-generic-medicine","officialUrl":"https://janaushadhi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmbjp","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"Generic medicines at 50-90% less than branded rates. 10,000+ PM Janaushadhi Kendras."},
  {"name":"Rashtriya Arogya Nidhi","state":"Central","category":"Health",
   "slug":"rashtriya-arogya-nidhi-financial-aid","officialUrl":"https://mohfw.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ran","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Financial aid up to ₹15 lakh for BPL patients with life-threatening diseases at govt hospitals."},
  {"name":"Niramaya Health Insurance","state":"Central","category":"Health",
   "slug":"niramaya-health-insurance-disabled-persons","officialUrl":"https://nhfdc.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/niramaya","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"₹1 lakh health insurance for persons with disability. ₹500/year premium (BPL: ₹250)."},
  {"name":"Rashtriya Bal Swasthya Karyakram","state":"Central","category":"Health",
   "slug":"rashtriya-bal-swasthya-karyakram-child-health","officialUrl":"https://nhm.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rbsk","priority":3,
   "estimatedMonthlySearches":12000,"langs":["en","hi"],
   "notes":"Free health screening for children 0-18 for 4 D's: defects, diseases, deficiencies, developmental delays."},
  {"name":"PM CARES for Children","state":"Central","category":"Health",
   "slug":"pm-cares-for-children-covid-orphans","officialUrl":"https://pmcaresforchildren.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmcfc","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Support for children orphaned by COVID-19. Free education, ₹10 lakh at 23, health cover."},
  {"name":"National AYUSH Mission","state":"Central","category":"Health",
   "slug":"national-ayush-mission-yoga-ayurveda","officialUrl":"https://ayush.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nam","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Promotion of Ayurveda, Yoga, Naturopathy, Unani, Siddha, Homeopathy through govt institutions."},
  {"name":"Pradhan Mantri Surakshit Matritva Abhiyan","state":"Central","category":"Health",
   "slug":"pmsma-free-antenatal-checkup-pregnant","officialUrl":"https://pmsma.nhp.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmsma","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Free antenatal checkup on 9th of every month for pregnant women at govt health facilities."},
  {"name":"PM Jan Arogya Yojana (Top-Up)","state":"Central","category":"Health",
   "slug":"pm-jan-arogya-yojana-top-up-insurance","officialUrl":"https://pmjay.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmjay-tu","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Additional ₹5 lakh insurance for senior citizens 70+ under Ayushman Bharat umbrella."},
  {"name":"National Mental Health Programme","state":"Central","category":"Health",
   "slug":"national-mental-health-programme-nmhp","officialUrl":"https://nhm.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nmhp","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"District Mental Health Programme. Free counselling, medicines at community health centres."},
  {"name":"PM TB Mukt Bharat Abhiyan","state":"Central","category":"Health",
   "slug":"pm-tb-mukt-bharat-ni-kshay-mitra","officialUrl":"https://nikshay.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ptmba","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Ni-kshay Mitra donors adopt TB patients. Nutritional support + care. Goal: TB-free India by 2025."},
  {"name":"Pradhan Mantri Jeevan Jyoti Bima Yojana","state":"Central","category":"Finance & Insurance",
   "slug":"pm-jeevan-jyoti-bima-yojana-pmjjby","officialUrl":"https://jansuraksha.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmjjby","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"₹2 lakh life insurance for ₹436/year. For 18-50 age group with bank account."},
  {"name":"Pradhan Mantri Suraksha Bima Yojana","state":"Central","category":"Finance & Insurance",
   "slug":"pm-suraksha-bima-yojana-pmsby-accident","officialUrl":"https://jansuraksha.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmsby","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"₹2 lakh accidental death/disability insurance for just ₹20/year. 18-70 age group."},

  # ─── EDUCATION ────────────────────────────────────────────────────
  {"name":"PM YASASVI Scholarship","state":"Central","category":"Education",
   "slug":"pm-yasasvi-scholarship-obc-ews-apply","officialUrl":"https://yet.nta.ac.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmyasasvi","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹75,000–₹1.25 lakh/year for Class 9-12 OBC/EWS/NT/DNT students. NTA conducts exam."},
  {"name":"Post Matric Scholarship SC Students","state":"Central","category":"Education",
   "slug":"post-matric-scholarship-sc-students-apply","officialUrl":"https://scholarships.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmssc","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Maintenance allowance + tuition fees for SC students in Class 11 to PhD. Apply via NSP."},
  {"name":"Post Matric Scholarship ST Students","state":"Central","category":"Education",
   "slug":"post-matric-scholarship-st-students-apply","officialUrl":"https://scholarships.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmsst","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"Maintenance allowance + tuition fees for ST students in Class 11 onwards. Apply via NSP."},
  {"name":"Post Matric Scholarship OBC","state":"Central","category":"Education",
   "slug":"post-matric-scholarship-obc-dr-ambedkar","officialUrl":"https://scholarships.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmsobc","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"Maintenance allowance for OBC students from Class 11 onwards. Dr. Ambedkar Post Matric Scholarship."},
  {"name":"NMMS Scholarship","state":"Central","category":"Education",
   "slug":"nmms-scholarship-class-8-apply","officialUrl":"https://scholarships.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nmms","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"₹12,000/year (₹1,000/month) for meritorious Class 9-12 students from economically weaker sections."},
  {"name":"AICTE Pragati Scholarship Girls","state":"Central","category":"Education",
   "slug":"aicte-pragati-scholarship-girls-technical","officialUrl":"https://www.aicte-india.org",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/aicte-pragati","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹50,000/year for girls in AICTE-approved technical institutes. First 2 girls per family."},
  {"name":"Ishan Uday Scholarship NE Students","state":"Central","category":"Education",
   "slug":"ishan-uday-scholarship-northeast-students","officialUrl":"https://scholarships.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ishanuday","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en"],
   "notes":"₹5,400-7,800/month for NE India students for undergraduate studies."},
  {"name":"Samagra Shiksha Abhiyan","state":"Central","category":"Education",
   "slug":"samagra-shiksha-abhiyan-school-education","officialUrl":"https://samagra.education.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ssa","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Integrated school education scheme. Textbooks, uniforms, MDM, digital education."},
  {"name":"PM POSHAN Mid Day Meal Scheme","state":"Central","category":"Education",
   "slug":"pm-poshan-mid-day-meal-scheme","officialUrl":"https://pmposhan.education.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmposhan","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Free hot cooked meal to all children in Class 1-8 in govt schools. 11.8 crore children daily."},
  {"name":"Eklavya Model Residential Schools","state":"Central","category":"Education",
   "slug":"eklavya-model-residential-schools-emrs","officialUrl":"https://emrs.tribal.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/emrs","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Residential schools for ST children in tribal areas. Free quality education Class 6-12."},
  {"name":"Pre Matric Scholarship SC ST Minorities","state":"Central","category":"Education",
   "slug":"pre-matric-scholarship-sc-st-minorities","officialUrl":"https://scholarships.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pms-pm","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"Scholarship for Class 1-10 students from SC/ST/OBC/Minority communities. Via NSP portal."},
  {"name":"MGNREGS 100 Days Work","state":"Central","category":"Labour & Employment",
   "slug":"mgnregs-100-days-work-guarantee-apply","officialUrl":"https://nrega.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mgnregs","priority":1,
   "estimatedMonthlySearches":200000,"langs":["en","hi"],
   "notes":"Guaranteed 100 days of unskilled wage employment per year. Apply at gram panchayat."},
]

existing = {s["slug"] for s in d["schemes"]}
added = [s for s in new_schemes if s["slug"] not in existing]
d["schemes"].extend(added)
f.write_text(json.dumps(d, indent=2, ensure_ascii=False))
print(f"Added {len(added)} schemes. Total: {len(d['schemes'])}")
