#!/usr/bin/env python3
"""Batch 5: MH, KA, GJ, TN, AP, TS, WB, Odisha, Kerala — English-only states"""
import json, pathlib

f = pathlib.Path("agents/scheme-pipeline-list.json")
d = json.loads(f.read_text())

new_schemes = [
  # ─── MAHARASHTRA ──────────────────────────────────────────────────
  {"name":"Maharashtra Mukhyamantri Saur Krishi Pump","state":"Maharashtra","category":"Agriculture",
   "slug":"maharashtra-saur-krishi-pump-solar-scheme","officialUrl":"https://mahadiscom.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mhskp","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en"],
   "notes":"Free/subsidised solar agricultural pump for farmers in Maharashtra. 5 HP at ₹25,000 max."},
  {"name":"Maharashtra Ek Rupee Clinic","state":"Maharashtra","category":"Health",
   "slug":"maharashtra-ek-rupee-clinic-government-hospital","officialUrl":"https://arogya.maharashtra.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mherc","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"Generic medicines at ₹1 per strip at govt hospitals. 600+ medicines available in Maharashtra."},
  {"name":"MahaDBT Scholarship Portal","state":"Maharashtra","category":"Education",
   "slug":"mahadbt-scholarship-maharashtra-apply","officialUrl":"https://mahadbt.maharashtra.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mhdbt","priority":1,
   "estimatedMonthlySearches":300000,"langs":["en"],
   "notes":"All Maharashtra government scholarships on one portal. SC/ST/OBC/EWS/minority. Huge search volume."},
  {"name":"Maharashtra Swadhaar Yojana Hostel","state":"Maharashtra","category":"Education",
   "slug":"maharashtra-swadhaar-yojana-sc-hostel-stipend","officialUrl":"https://sjsa.maharashtra.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mhswyd","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en"],
   "notes":"₹51,000-60,000/year for SC/NavBauddha students living outside hostel for higher education in Maharashtra."},
  {"name":"Maharashtra Rajshri Shahu Scholarship","state":"Maharashtra","category":"Education",
   "slug":"maharashtra-rajshri-shahu-scholarship-obc","officialUrl":"https://mahadbt.maharashtra.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mhrsso","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"Post-matric scholarship for OBC students in Maharashtra. ₹8,000-15,000/year."},
  {"name":"Mahatma Phule Jan Arogya Yojana","state":"Maharashtra","category":"Health",
   "slug":"mahatma-phule-jan-arogya-yojana-maharashtra","officialUrl":"https://www.jeevandayee.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpjay","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"₹5 lakh health insurance for BPL/yellow ration card families in Maharashtra. 996 procedures."},
  {"name":"Maharashtra Annasaheb Patil Loan Guarantee","state":"Maharashtra","category":"Business & Finance",
   "slug":"maharashtra-annasaheb-patil-loan-maratha-entrepreneur","officialUrl":"https://mahaswayam.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mhapml","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en"],
   "notes":"Loan guarantee up to ₹3 crore for Maratha community entrepreneurs in Maharashtra."},

  # ─── KARNATAKA (additions) ────────────────────────────────────────
  {"name":"Karnataka Raitha Siri Scheme","state":"Karnataka","category":"Agriculture",
   "slug":"karnataka-raitha-siri-farmer-insurance","officialUrl":"https://raitamitra.kar.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/krss","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"Accident insurance ₹5 lakh for farmers in Karnataka. Crop damage compensation. Free on registration."},
  {"name":"Karnataka Shaadi Bhagya Marriage Grant","state":"Karnataka","category":"Women & Family",
   "slug":"karnataka-shaadi-bhagya-marriage-grant-sc-st","officialUrl":"https://socialsecurity.karnataka.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ksbmg","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"₹50,000 marriage grant for SC/ST/OBC/Minority girls in Karnataka."},
  {"name":"Karnataka Suvarna Gramodaya Yojana","state":"Karnataka","category":"Infrastructure",
   "slug":"karnataka-suvarna-gramodaya-rural-development","officialUrl":"https://rdpr.karnataka.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ksgy","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en"],
   "notes":"Integrated rural village development scheme — roads, drainage, lighting, water in Karnataka."},
  {"name":"Karnataka Swalambi Shahari Pension","state":"Karnataka","category":"Social Welfare",
   "slug":"karnataka-sandhya-suraksha-old-age-pension","officialUrl":"https://sevasindhu.karnataka.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/kssp","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"₹600-1,000/month old age/widow/disability pension in Karnataka. Apply at Seva Sindhu."},
  {"name":"Vidyasiri Karnataka Scholarship SC ST","state":"Karnataka","category":"Education",
   "slug":"vidyasiri-karnataka-scholarship-sc-st-apply","officialUrl":"https://sevasindhu.karnataka.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/kvssi","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en"],
   "notes":"Post-matric scholarship for SC/ST students in Karnataka. Apply via Seva Sindhu portal."},

  # ─── GUJARAT ──────────────────────────────────────────────────────
  {"name":"Mukhyamantri Mahila Utkarsh Yojana Gujarat","state":"Gujarat","category":"Women & Family",
   "slug":"mukhyamantri-mahila-utkarsh-yojana-gujarat","officialUrl":"https://mmuy.gujarat.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/gjmmuy","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en"],
   "notes":"0% interest loan for SHG women in Gujarat. ₹1 lakh per member. 10 lakh women covered."},
  {"name":"iKhedut Portal Gujarat Farmer Schemes","state":"Gujarat","category":"Agriculture",
   "slug":"ikhedut-portal-gujarat-farmer-schemes","officialUrl":"https://ikhedut.gujarat.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/gjikh","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en"],
   "notes":"Single portal for all Gujarat farmer schemes — tractor, drip irrigation, power pump subsidies."},
  {"name":"Mukhyamantri Amrutum Yojana Gujarat","state":"Gujarat","category":"Health",
   "slug":"mukhyamantri-amrutum-yojana-gujarat-health","officialUrl":"https://health.gujarat.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/gjmay","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"₹10 lakh health insurance for BPL families in Gujarat. Cashless at empanelled hospitals."},
  {"name":"VANBANDHU Kalyan Yojana Gujarat","state":"Gujarat","category":"Social Welfare",
   "slug":"vanbandhu-kalyan-yojana-gujarat-tribal","officialUrl":"https://tribal.gujarat.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/gjvky","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"Welfare for tribal communities in Gujarat — housing, education, health, livelihood."},
  {"name":"Kisan Suryoday Yojana Gujarat","state":"Gujarat","category":"Agriculture",
   "slug":"kisan-suryoday-yojana-gujarat-3-phase-power","officialUrl":"https://agri.gujarat.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/gjksy","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en"],
   "notes":"3-phase electricity to all Gujarat farmers from 5 AM to 9 PM for irrigation pumps."},
  {"name":"Gujarat Scholarship for SC Students","state":"Gujarat","category":"Education",
   "slug":"gujarat-scholarship-sc-students-e-samaj-kalyan","officialUrl":"https://esamajkalyan.gujarat.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/gjscs","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en"],
   "notes":"Pre/post matric scholarship for SC students. Apply at esamajkalyan.gujarat.gov.in"},

  # ─── TAMIL NADU ───────────────────────────────────────────────────
  {"name":"Kalaignar Magalir Urimai Thogai","state":"Tamil Nadu","category":"Women & Family",
   "slug":"kalaignar-magalir-urimai-thogai-1000-women","officialUrl":"https://tn.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tnkmut","priority":1,
   "estimatedMonthlySearches":200000,"langs":["en"],
   "notes":"₹1,000/month to women household heads in Tamil Nadu. One of highest-searched TN schemes."},
  {"name":"Murasoli Scheme Tamil Nadu","state":"Tamil Nadu","category":"Social Welfare",
   "slug":"murasoli-scheme-tamil-nadu-disabled-pension","officialUrl":"https://tn.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tnms","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"₹1,000/month pension for disabled persons in Tamil Nadu. Apply at district social welfare office."},
  {"name":"Tamil Nadu CM Breakfast Scheme","state":"Tamil Nadu","category":"Education",
   "slug":"tamil-nadu-cm-breakfast-scheme-students","officialUrl":"https://tnschools.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tncmbs","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en"],
   "notes":"Free breakfast for government school students Class 1-5 in Tamil Nadu."},
  {"name":"TN Pudhumai Penn Scholarship","state":"Tamil Nadu","category":"Education",
   "slug":"tn-pudhumai-penn-scholarship-government-school-girls","officialUrl":"https://tnscholarships.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tnpps","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"₹1,000/month for govt school girl students pursuing higher education in Tamil Nadu."},
  {"name":"Amma Unavagam Tamil Nadu","state":"Tamil Nadu","category":"Social Welfare",
   "slug":"amma-unavagam-cheap-canteen-tamil-nadu","officialUrl":"https://tn.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tnau","priority":3,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"Subsidised food at ₹5 per meal (rice + 2 side dishes) at 500+ canteens across Tamil Nadu."},
  {"name":"TN Chief Minister Health Insurance Scheme","state":"Tamil Nadu","category":"Health",
   "slug":"tn-cm-health-insurance-scheme-apply","officialUrl":"https://cmchis.tn.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tncmhis","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en"],
   "notes":"₹5 lakh health cover for TN families with annual income <₹1.2 lakh. cmchis.tn.gov.in"},

  # ─── ANDHRA PRADESH ───────────────────────────────────────────────
  {"name":"YSR Rythu Bharosa Andhra Pradesh","state":"Andhra Pradesh","category":"Agriculture",
   "slug":"ysr-rythu-bharosa-ap-farmer-support","officialUrl":"https://ysrrythubharosa.ap.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/apyrb","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en"],
   "notes":"₹13,500/year to all farmer families in AP (₹7,500 state + PM Kisan ₹6,000). Status check online."},
  {"name":"Jagananna Amma Vodi AP","state":"Andhra Pradesh","category":"Education",
   "slug":"jagananna-amma-vodi-ap-school-mothers","officialUrl":"https://ammavodi.ap.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/apjav","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en"],
   "notes":"₹15,000/year to mothers who send children to govt schools in AP. DBT to mother's account."},
  {"name":"YSR Aarogyasri Health Scheme AP","state":"Andhra Pradesh","category":"Health",
   "slug":"ysr-aarogyasri-health-scheme-ap","officialUrl":"https://ysraarogyasri.ap.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/apyaas","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"₹5 lakh + ₹10 lakh health insurance for BPL families in AP. 2,500+ procedures covered."},
  {"name":"YSR Pension Kanuka AP","state":"Andhra Pradesh","category":"Social Welfare",
   "slug":"ysr-pension-kanuka-ap-social-security","officialUrl":"https://navasakam.ap.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/apypk","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en"],
   "notes":"₹3,000-3,500/month pension for old age, widow, disability, fishermen in AP."},
  {"name":"Jagananna Housing Scheme AP","state":"Andhra Pradesh","category":"Housing",
   "slug":"jagananna-housing-scheme-ap-navaratnalu","officialUrl":"https://navaratnalu.ap.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/apjhs","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en"],
   "notes":"Free house with ₹1.8 lakh grant for homeless BPL families in AP. Check status at navaratnalu.ap.gov.in"},

  # ─── TELANGANA ────────────────────────────────────────────────────
  {"name":"Rythu Bandhu Telangana Farmer Investment","state":"Telangana","category":"Agriculture",
   "slug":"rythu-bandhu-telangana-farmer-investment","officialUrl":"https://rythubandhu.telangana.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tsrb","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en"],
   "notes":"₹10,000/acre/year to all farm land owners in Telangana. ₹5,000 per Kharif and Rabi."},
  {"name":"Rythu Bima Telangana Farmer Insurance","state":"Telangana","category":"Agriculture",
   "slug":"rythu-bima-telangana-farmer-life-insurance","officialUrl":"https://rythubandhu.telangana.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tsrbi","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en"],
   "notes":"₹5 lakh life insurance for all 4-72 age farmers in Telangana. Free, government pays premium."},
  {"name":"Kalyana Lakshmi Shaadi Mubarak Telangana","state":"Telangana","category":"Women & Family",
   "slug":"kalyana-lakshmi-shaadi-mubarak-telangana-marriage","officialUrl":"https://telanganaepass.cgg.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tskl","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"₹1,00,116 marriage grant for SC/ST (Kalyana Lakshmi) and Minorities (Shaadi Mubarak) in Telangana."},
  {"name":"KCR Kit Telangana Pregnant Women","state":"Telangana","category":"Health",
   "slug":"kcr-kit-telangana-pregnant-women-kit","officialUrl":"https://hmfw.telangana.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tskcr","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en"],
   "notes":"16-item baby kit + ₹12,000 cash incentive for pregnant women in Telangana delivering at govt hospitals."},
  {"name":"TS Aasara Pension","state":"Telangana","category":"Social Welfare",
   "slug":"ts-aasara-pension-telangana-old-age","officialUrl":"https://aasara.telangana.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tsap","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en"],
   "notes":"₹2,016-4,016/month pension for old age, widow, disabled, toddy tappers, weavers in Telangana."},

  # ─── WEST BENGAL ──────────────────────────────────────────────────
  {"name":"Lakshmir Bhandar West Bengal","state":"West Bengal","category":"Women & Family",
   "slug":"lakshmir-bhandar-west-bengal-monthly-allowance","officialUrl":"https://wb.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/wblb","priority":1,
   "estimatedMonthlySearches":200000,"langs":["en"],
   "notes":"₹500/month (General) / ₹1,000/month (SC/ST) for women household heads in WB. Duare Sarkar."},
  {"name":"Kanyashree Prakalpa West Bengal","state":"West Bengal","category":"Women & Family",
   "slug":"kanyashree-prakalpa-west-bengal-girls","officialUrl":"https://wbkanyashree.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/wbkp","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en"],
   "notes":"₹1,000/year (K1) and ₹25,000 one-time (K2 at 18+) for unmarried girls in WB schools."},
  {"name":"Krishak Bandhu West Bengal","state":"West Bengal","category":"Agriculture",
   "slug":"krishak-bandhu-west-bengal-farmer-support","officialUrl":"https://krishakbandhu.net",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/wbkrb","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"₹10,000/year for farmers with 1+ acre; ₹4,000 for <1 acre in WB. Free life insurance ₹2 lakh."},
  {"name":"Rupashree Prakalpa West Bengal Marriage","state":"West Bengal","category":"Women & Family",
   "slug":"rupashree-prakalpa-west-bengal-marriage-grant","officialUrl":"https://wb.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/wbrp","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en"],
   "notes":"₹25,000 one-time grant for marriage of economically backward girls in WB (family income <₹1.5 lakh)."},
  {"name":"Duare Sarkar West Bengal Services","state":"West Bengal","category":"Digital Services",
   "slug":"duare-sarkar-west-bengal-doorstep-services","officialUrl":"https://wb.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/wbds","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en"],
   "notes":"30+ government schemes delivered at doorstep camps in WB. Lakshmir Bhandar, health cards, pensions."},

  # ─── ODISHA (additions) ────────────────────────────────────────────
  {"name":"KALIA Scheme Odisha Farmers","state":"Odisha","category":"Agriculture",
   "slug":"kalia-scheme-odisha-farmer-support","officialUrl":"https://kalia.odisha.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/odks","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en"],
   "notes":"₹25,000 over 5 seasons for small/marginal farmers in Odisha. ₹12,500 for landless laborers."},
  {"name":"Biju Swasthya Kalyan Yojana Odisha","state":"Odisha","category":"Health",
   "slug":"biju-swasthya-kalyan-yojana-odisha-health","officialUrl":"https://bsky.odisha.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/odbsky","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en"],
   "notes":"₹5 lakh (women: ₹10 lakh) health insurance for BPL families in Odisha at empanelled hospitals."},
  {"name":"Mission Shakti Odisha SHG","state":"Odisha","category":"Women & Family",
   "slug":"mission-shakti-odisha-shg-women","officialUrl":"https://missionshakti.odisha.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/odmss","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"7 million SHG women in Odisha. Savings, credit, livelihood, capacity building. ₹1 lakh revolving fund."},

  # ─── KERALA ───────────────────────────────────────────────────────
  {"name":"Kerala Karshaka Kshemanidhi Farmer Pension","state":"Kerala","category":"Agriculture",
   "slug":"kerala-karshaka-kshemanidhi-farmer-pension","officialUrl":"https://keralaagriculture.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/klkkf","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"₹1,100/month pension for registered farmers and agricultural workers in Kerala after 60."},
  {"name":"Snehapoorvam Scholarship Kerala","state":"Kerala","category":"Education",
   "slug":"snehapoorvam-scholarship-kerala-orphans","officialUrl":"https://swd.kerala.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/klsps","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en"],
   "notes":"₹300-1,000/month scholarship for orphan children and children of jailed parents in Kerala."},
  {"name":"Kudumbashree Mission Kerala","state":"Kerala","category":"Women & Family",
   "slug":"kudumbashree-mission-kerala-shg-microenterprise","officialUrl":"https://kudumbashree.org",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/klkm","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en"],
   "notes":"5 million women in 2.77 lakh SHGs. Microcredit, agri enterprises, urban wage employment."},
  {"name":"Kerala Arogyakeralam Health Insurance","state":"Kerala","category":"Health",
   "slug":"kerala-arogyakeralam-karunya-health-insurance","officialUrl":"https://arogyakeralam.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/klakh","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en"],
   "notes":"₹5 lakh health insurance under Karunya Arogya Suraksha Padhathi (KASP) for BPL families in Kerala."},
  {"name":"Kerala Chiri Chiriyath Scheme Disability","state":"Kerala","category":"Social Welfare",
   "slug":"kerala-disability-pension-social-security","officialUrl":"https://socialwelfare.kerala.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/klssd","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en"],
   "notes":"₹1,600/month disability pension in Kerala. 40%+ disability certificate required."},
]

existing = {s["slug"] for s in d["schemes"]}
added = [s for s in new_schemes if s["slug"] not in existing]
d["schemes"].extend(added)
f.write_text(json.dumps(d, indent=2, ensure_ascii=False))
print(f"Added {len(added)} schemes. Total: {len(d['schemes'])}")
