#!/usr/bin/env python3
"""Batch 3: State schemes — Uttar Pradesh (25), Bihar (12), Madhya Pradesh (12)"""
import json, pathlib

f = pathlib.Path("agents/scheme-pipeline-list.json")
d = json.loads(f.read_text())

new_schemes = [
  # ─── UTTAR PRADESH ────────────────────────────────────────────────
  {"name":"UP Scholarship Pre Matric","state":"Uttar Pradesh","category":"Education",
   "slug":"up-scholarship-pre-matric-apply-online","officialUrl":"https://scholarship.up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/up-pms","priority":1,
   "estimatedMonthlySearches":500000,"langs":["en","hi"],
   "notes":"Pre-matric scholarship for SC/ST/OBC/minority students in UP. Apply at scholarship.up.gov.in. Massive search volume every cycle."},
  {"name":"UP Scholarship Post Matric","state":"Uttar Pradesh","category":"Education",
   "slug":"up-scholarship-post-matric-apply-online","officialUrl":"https://scholarship.up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/up-postms","priority":1,
   "estimatedMonthlySearches":600000,"langs":["en","hi"],
   "notes":"Post-matric scholarship for SC/ST/OBC/minority students in UP. Most searched UP scheme."},
  {"name":"UP BC Sakhi Yojana","state":"Uttar Pradesh","category":"Women & Family",
   "slug":"up-bc-sakhi-yojana-banking-correspondent","officialUrl":"https://up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upbcs","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"Women appointed as Bank Correspondent Sakhi. ₹4,000/month for 6 months + commission."},
  {"name":"Mukhyamantri Abhyudaya Yojana UP","state":"Uttar Pradesh","category":"Education",
   "slug":"mukhyamantri-abhyudaya-yojana-up-free-coaching","officialUrl":"https://abhyuday.up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/muay","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Free coaching for UPSC/UPPSC/JEE/NEET/NDA/SSB in govt colleges. High demand in UP."},
  {"name":"UP Mukhyamantri Yuva Swarozgar Yojana","state":"Uttar Pradesh","category":"Business & Finance",
   "slug":"up-yuva-swarozgar-yojana-loan-subsidy","officialUrl":"https://diupmsme.upsdc.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upys","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"Loan up to ₹25 lakh with 25% subsidy for educated youth in UP. Service sector up to ₹10 lakh."},
  {"name":"UP Free Laptop Yojana","state":"Uttar Pradesh","category":"Education",
   "slug":"up-free-laptop-yojana-students","officialUrl":"https://upcmo.up.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upfl","priority":2,
   "estimatedMonthlySearches":300000,"langs":["en","hi"],
   "notes":"Free laptop for students with 65%+ marks in Class 10/12. Very high search volume in UP."},
  {"name":"UP Kisan Karj Mafi Yojana","state":"Uttar Pradesh","category":"Agriculture",
   "slug":"up-kisan-karj-mafi-farm-loan-waiver","officialUrl":"https://upkisankarjrahat.upsdc.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upkkmf","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Farm loan waiver scheme for small and marginal farmers in UP. Check status online."},
  {"name":"UP Mathrubhumi Yojana","state":"Uttar Pradesh","category":"Infrastructure",
   "slug":"up-mathrubhumi-yojana-village-development","officialUrl":"https://mathrubhumi.up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upmby","priority":3,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Individuals/NRIs fund village infrastructure. 50% govt + 50% individual. Schools, roads, health centres."},
  {"name":"UP MSME Loan Mela","state":"Uttar Pradesh","category":"Business & Finance",
   "slug":"up-msme-loan-mela-odop","officialUrl":"https://odopup.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upml","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"One District One Product (ODOP) — loans and subsidies for district-specific craft/product businesses."},
  {"name":"UP Mahila Samarthya Yojana","state":"Uttar Pradesh","category":"Women & Family",
   "slug":"up-mahila-samarthya-yojana-women-skill","officialUrl":"https://mahilakalyan.up.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upmsy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Skill and livelihood training for rural women. SHG based model. Free training + market linkage."},
  {"name":"UP Mukhyamantri Krishak Durghatna Bima","state":"Uttar Pradesh","category":"Agriculture",
   "slug":"up-krishak-durghatna-bima-farmer-insurance","officialUrl":"https://upagripardarshi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upkdby","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"₹5 lakh accidental insurance for farmers in UP. Free for all registered farmers."},
  {"name":"UP Bhagya Laxmi Yojana","state":"Uttar Pradesh","category":"Women & Family",
   "slug":"up-bhagya-laxmi-yojana-girl-birth-benefit","officialUrl":"https://mahilakalyan.up.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upbly","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"₹50,000 bond at girl's birth for BPL families. ₹5,100 nutrition grant for mother. Class 6-12 scholarships."},
  {"name":"UP Startup Policy Yojana","state":"Uttar Pradesh","category":"Business & Finance",
   "slug":"up-startup-policy-yojana-seed-fund","officialUrl":"https://invest.up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upsp","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Seed fund up to ₹25 lakh, mentorship, and SIDBI support for UP startups."},
  {"name":"UP Solar Pump Scheme","state":"Uttar Pradesh","category":"Agriculture",
   "slug":"up-solar-pump-scheme-farmers-subsidy","officialUrl":"https://upagripardarshi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upsps","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"UP government 70% subsidy on solar irrigation pumps for farmers. Apply via agri dept."},
  {"name":"Mukhyamantri Parivar Kalyan Yojana UP","state":"Uttar Pradesh","category":"Social Welfare",
   "slug":"mukhyamantri-parivar-kalyan-yojana-up","officialUrl":"https://up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upmpky","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹2 lakh on accidental death + scholarship for children + pension for widowed spouse."},
  {"name":"UP Vidhwa Pension","state":"Uttar Pradesh","category":"Social Welfare",
   "slug":"up-vidhwa-pension-yojana-widow-pension","officialUrl":"https://sspy-up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upvp","priority":2,
   "estimatedMonthlySearches":200000,"langs":["en","hi"],
   "notes":"₹1,000/month widow pension in UP. Apply at sspy-up.gov.in. Check status online."},
  {"name":"UP Vridha Pension","state":"Uttar Pradesh","category":"Social Welfare",
   "slug":"up-vridha-pension-yojana-old-age","officialUrl":"https://sspy-up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upvrp","priority":2,
   "estimatedMonthlySearches":300000,"langs":["en","hi"],
   "notes":"₹1,000/month old age pension (60+) in UP. Apply at sspy-up.gov.in. Huge search volume."},
  {"name":"UP Divyang Pension","state":"Uttar Pradesh","category":"Social Welfare",
   "slug":"up-divyang-pension-handicapped-pension","officialUrl":"https://sspy-up.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/updvp","priority":2,
   "estimatedMonthlySearches":150000,"langs":["en","hi"],
   "notes":"₹1,000/month disability pension in UP. Apply at sspy-up.gov.in."},
  {"name":"UP Saur Urja Sahayata Yojana","state":"Uttar Pradesh","category":"Energy",
   "slug":"up-saur-urja-sahayata-solar-free-electricity","officialUrl":"https://upneda.org.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upsus","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Free solar power connection for BPL families in UP. 2-3 LED bulbs and fan. Under rural electrification."},
  {"name":"UP CM Kisan Sarvhit Bima Yojana","state":"Uttar Pradesh","category":"Agriculture",
   "slug":"up-kisan-sarvhit-bima-comprehensive-insurance","officialUrl":"https://upagripardarshi.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upksby","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Comprehensive accident + hospitalization insurance for UP farmers and their families."},
  {"name":"UP Janai Suraksha Yojana","state":"Uttar Pradesh","category":"Women & Family",
   "slug":"up-janani-suraksha-yojana-delivery-cash","officialUrl":"https://nhm.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upjsy","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"UP state top-up on Janani Suraksha. ₹1,500 extra for home delivery, extra for institutional birth."},
  {"name":"UP ODOP Product Training Subsidy","state":"Uttar Pradesh","category":"Skill & Training",
   "slug":"up-odop-training-subsidy-district-craft","officialUrl":"https://odopup.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upodop","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Free skill training + tools for local craft (chikankari, zari, woodwork, etc.) under ODOP mission."},
  {"name":"CM Swarozgar Yojana UP","state":"Uttar Pradesh","category":"Business & Finance",
   "slug":"cm-swarozgar-yojana-up-business-loan","officialUrl":"https://diupmsme.upsdc.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/cmsyup","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"Self-employment loans for artisans and micro-entrepreneurs in UP. ₹1-25 lakh range."},
  {"name":"UP Mukhyamantri Nishulk Boring Yojana","state":"Uttar Pradesh","category":"Agriculture",
   "slug":"up-nishulk-boring-yojana-free-tube-well","officialUrl":"https://minorirrigationup.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upnby","priority":3,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Free tube well boring for small/marginal farmers in UP with up to 0.2 ha land."},
  {"name":"UP Gopalak Yojana","state":"Uttar Pradesh","category":"Agriculture",
   "slug":"up-gopalak-yojana-dairy-loan","officialUrl":"https://upahd.upsdc.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/upgy","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Loan up to ₹1.8 lakh for purchasing 5-10 cows/buffaloes in UP for dairy farming."},

  # ─── BIHAR ────────────────────────────────────────────────────────
  {"name":"Mukhyamantri Kanya Utthan Yojana Bihar","state":"Bihar","category":"Women & Family",
   "slug":"mukhyamantri-kanya-utthan-yojana-bihar","officialUrl":"https://edudbt.bih.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mkuy","priority":1,
   "estimatedMonthlySearches":200000,"langs":["en","hi"],
   "notes":"₹50,000 to girls from birth to graduation in 5+ installments in Bihar. Very high search volume."},
  {"name":"Bihar Student Credit Card","state":"Bihar","category":"Education",
   "slug":"bihar-student-credit-card-apply","officialUrl":"https://www.7nishchay-yuvaupmission.bihar.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bscc","priority":1,
   "estimatedMonthlySearches":150000,"langs":["en","hi"],
   "notes":"₹4 lakh loan at 4% interest for higher education. 0% for girls/disabled. No collateral."},
  {"name":"Bihar Laghu Udyami Yojana","state":"Bihar","category":"Business & Finance",
   "slug":"bihar-laghu-udyami-yojana-entrepreneur-grant","officialUrl":"https://udyami.bihar.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bluy","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"₹2 lakh grant for BPL/SC/ST entrepreneurs to start business. 94 product categories."},
  {"name":"Bihar Har Ghar Bijli Yojana","state":"Bihar","category":"Energy",
   "slug":"bihar-har-ghar-bijli-yojana","officialUrl":"https://hargharbijli.bsphcl.co.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bhgby","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"Free electricity connection for all households in Bihar. Check status + apply online."},
  {"name":"Bihar Cycle Yojana","state":"Bihar","category":"Education",
   "slug":"bihar-mukhyamantri-cycle-yojana-girls","officialUrl":"https://state.bihar.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bmcy","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Free bicycle for girls in Class 9 in govt schools. ₹3,000 DBT to account."},
  {"name":"Bihar Kishori Swasthya Karyakram","state":"Bihar","category":"Health",
   "slug":"bihar-kishori-swasthya-karyakram-nutrition","officialUrl":"https://icdsonline.bih.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bksk","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Iron + folic acid supplements, nutrition counselling, sanitary napkins for adolescent girls 14-18."},
  {"name":"Bihar Kushal Yuva Programme","state":"Bihar","category":"Skill & Training",
   "slug":"bihar-kushal-yuva-programme-skill-training","officialUrl":"https://skillmissionbihar.org",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bkyp","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"Communication + IT skills + life skills training for Bihar youth aged 15-28. 240 hours."},
  {"name":"Bihar Vridhjan Pension Yojana","state":"Bihar","category":"Social Welfare",
   "slug":"bihar-vridhjan-pension-yojana-mukhyamantri","officialUrl":"https://sspmis.bihar.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bvpy","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"₹400/month for 60-79 age; ₹500/month for 80+. Apply at sspmis.bihar.gov.in."},
  {"name":"Bihar RTPS Birth Certificate","state":"Bihar","category":"Digital Services",
   "slug":"bihar-rtps-birth-certificate-caste-domicile","officialUrl":"https://serviceonline.bihar.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/brtps","priority":1,
   "estimatedMonthlySearches":400000,"langs":["en","hi"],
   "notes":"Online birth/death/caste/domicile/income certificates in Bihar via serviceonline.bihar.gov.in."},
  {"name":"Bihar Diesel Anudan Yojana","state":"Bihar","category":"Agriculture",
   "slug":"bihar-diesel-anudan-yojana-farmer-subsidy","officialUrl":"https://dbtagriculture.bihar.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bday","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"Diesel subsidy ₹50/litre for irrigation pump up to 8 hours/acre for Bihar farmers."},
  {"name":"Bihar Krishi Input Anudan","state":"Bihar","category":"Agriculture",
   "slug":"bihar-krishi-input-anudan-flood-drought-farmers","officialUrl":"https://dbtagriculture.bihar.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bkia","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"₹8,500-13,500/ha compensation for crop damage due to flood/drought in Bihar."},
  {"name":"Bihar Aaksmik Fasal Yojana","state":"Bihar","category":"Agriculture",
   "slug":"bihar-aaksmik-fasal-yojana-contingency-crop","officialUrl":"https://dbtagriculture.bihar.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bafy","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Free mini-kits (seeds) for alternate crops when main crop fails due to drought in Bihar."},

  # ─── MADHYA PRADESH ───────────────────────────────────────────────
  {"name":"Mukhyamantri Ladli Bahna Yojana","state":"Madhya Pradesh","category":"Women & Family",
   "slug":"mukhyamantri-ladli-bahna-yojana-mp","officialUrl":"https://cmladlibahna.mp.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mmlby","priority":1,
   "estimatedMonthlySearches":400000,"langs":["en","hi"],
   "notes":"₹1,250/month to married women in MP aged 23-60. ₹1.5 crore DBT monthly. Huge search volume."},
  {"name":"Ladli Laxmi Yojana MP","state":"Madhya Pradesh","category":"Women & Family",
   "slug":"ladli-laxmi-yojana-mp-girl-child","officialUrl":"https://ladlilaxmi.mp.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/llym","priority":2,
   "estimatedMonthlySearches":150000,"langs":["en","hi"],
   "notes":"₹1.43 lakh support in installments from birth to Class 12 for girl child in MP."},
  {"name":"MP Mukhyamantri Krishak Mitra Yojana","state":"Madhya Pradesh","category":"Agriculture",
   "slug":"mp-krishak-mitra-yojana-electricity-pump","officialUrl":"https://mpwrd.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpkmmy","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"3-HP electric pump + pipeline for farmers in MP at 50% cost. Electricity connection in 3 months."},
  {"name":"MP Mukhyamantri Udyam Kranti Yojana","state":"Madhya Pradesh","category":"Business & Finance",
   "slug":"mp-mukhyamantri-udyam-kranti-yojana-loan","officialUrl":"https://samast.mponline.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpmuky","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"Collateral-free loan ₹1-50 lakh for new businesses. 3% interest subsidy for 7 years in MP."},
  {"name":"MP Mukhyamantri Awasiya Bhu-Adhikar Yojana","state":"Madhya Pradesh","category":"Housing",
   "slug":"mp-awasiya-bhu-adhikar-yojana-land-rights","officialUrl":"https://saara.mp.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpabay","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Free residential land to landless rural families in MP. Check SAARA portal for status."},
  {"name":"MP Mukhyamantri Tirth Darshan Yojana","state":"Madhya Pradesh","category":"Social Welfare",
   "slug":"mp-tirth-darshan-yojana-free-pilgrimage","officialUrl":"https://tirthdarshan.mp.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mptdy","priority":3,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Free pilgrimage to religious sites (Shirdi, Tirupati, Vaishno Devi, etc.) for seniors 60+ in MP."},
  {"name":"MP Viklang Pension","state":"Madhya Pradesh","category":"Social Welfare",
   "slug":"mp-viklang-pension-disability-pension","officialUrl":"https://socialsecurity.mp.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpvp","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"₹600/month disability pension in MP. Apply via Social Justice portal. Check status online."},
  {"name":"MP Vriddha Pension","state":"Madhya Pradesh","category":"Social Welfare",
   "slug":"mp-vriddha-pension-old-age-pension","officialUrl":"https://socialsecurity.mp.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpvrp","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"₹600/month old age pension for seniors 60+ in MP. socialsecurity.mp.gov.in"},
  {"name":"MP Mukhyamantri Swarojgar Yojana","state":"Madhya Pradesh","category":"Business & Finance",
   "slug":"mp-mukhyamantri-swarojgar-yojana-loan","officialUrl":"https://msme.mponline.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpmsy","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"Interest-free loan for new enterprise in MP. ₹50,000–₹10 lakh. 15% margin money subsidy."},
  {"name":"MP Kanya Vivah Nikah Yojana","state":"Madhya Pradesh","category":"Women & Family",
   "slug":"mp-kanya-vivah-nikah-yojana-marriage-grant","officialUrl":"https://vivah.samagra.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpkvny","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"₹55,000 for marriage expenses (gifts + household items + cash) for BPL/SC/ST girls in MP."},
  {"name":"MP E-Uparjan Wheat MSP","state":"Madhya Pradesh","category":"Agriculture",
   "slug":"mp-e-uparjan-wheat-procurement-msp","officialUrl":"https://mpeuparjan.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpeu","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Wheat/paddy procurement at MSP from farmers in MP. Register at mpeuparjan.nic.in."},
  {"name":"MP Mukhyamantri Gaon Ki Beti Yojana","state":"Madhya Pradesh","category":"Education",
   "slug":"mp-gaon-ki-beti-yojana-rural-girls-scholarship","officialUrl":"https://scholarshipportal.mp.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/mpgkby","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹500/month (10 months/year) for rural girls who scored 60%+ in Class 12 in MP."},
]

existing = {s["slug"] for s in d["schemes"]}
added = [s for s in new_schemes if s["slug"] not in existing]
d["schemes"].extend(added)
f.write_text(json.dumps(d, indent=2, ensure_ascii=False))
print(f"Added {len(added)} schemes. Total: {len(d['schemes'])}")
