#!/usr/bin/env python3
"""Batch 2: Central — Finance, Employment, Business, Social Security, Energy, Infrastructure"""
import json, pathlib

f = pathlib.Path("agents/scheme-pipeline-list.json")
d = json.loads(f.read_text())

new_schemes = [
  # ─── FINANCE & BANKING ────────────────────────────────────────────
  {"name":"PM Jeevan Jyoti Bima Yojana","state":"Central","category":"Finance & Insurance",
   "slug":"pm-jeevan-jyoti-bima-yojana-pmjjby","officialUrl":"https://jansuraksha.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmjjby","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"₹2 lakh life insurance for ₹436/year. 18-50 age group with savings bank account."},
  {"name":"PM Suraksha Bima Yojana","state":"Central","category":"Finance & Insurance",
   "slug":"pm-suraksha-bima-yojana-pmsby-accident","officialUrl":"https://jansuraksha.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmsby","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"₹2 lakh accidental death/disability insurance for ₹20/year. 18-70 age group."},
  {"name":"National Pension System NPS","state":"Central","category":"Finance & Savings",
   "slug":"national-pension-system-nps-account-open","officialUrl":"https://enps.nsdl.com",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nps","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Voluntary pension scheme. Market-linked returns. 60% lump sum + 40% annuity at retirement."},
  {"name":"Kisan Vikas Patra","state":"Central","category":"Finance & Savings",
   "slug":"kisan-vikas-patra-kvp-post-office","officialUrl":"https://indiapost.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/kvp","priority":3,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Post office savings: money doubles in ~115 months (7.5% p.a.). Min ₹1,000 investment."},
  {"name":"Senior Citizen Savings Scheme","state":"Central","category":"Finance & Savings",
   "slug":"senior-citizen-savings-scheme-scss","officialUrl":"https://indiapost.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/scss","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"8.2% interest for seniors (60+). Max ₹30 lakh. Available at post offices and banks."},
  {"name":"Public Provident Fund PPF","state":"Central","category":"Finance & Savings",
   "slug":"public-provident-fund-ppf-account","officialUrl":"https://indiapost.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ppf","priority":2,
   "estimatedMonthlySearches":150000,"langs":["en","hi"],
   "notes":"EEE tax savings. 7.1% interest. 15-year lock-in. Max ₹1.5 lakh/year."},

  # ─── EMPLOYMENT & SKILL ────────────────────────────────────────────
  {"name":"PM Kaushal Vikas Yojana","state":"Central","category":"Skill & Training",
   "slug":"pm-kaushal-vikas-yojana-pmkvy-training","officialUrl":"https://pmkvyofficial.org",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmkvy","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"Free skill training + ₹8,000 reward + placement support. 300+ job roles. NSQF aligned."},
  {"name":"Deen Dayal Upadhyay Grameen Kaushalya Yojana","state":"Central","category":"Skill & Training",
   "slug":"ddu-gky-rural-skill-training-placement","officialUrl":"https://ddugky.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ddu-gky","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Free skill training + job placement for rural youth aged 15-35. 100% residential training."},
  {"name":"NAPS National Apprenticeship Promotion","state":"Central","category":"Skill & Training",
   "slug":"national-apprenticeship-promotion-scheme-naps","officialUrl":"https://apprenticeshipindia.org",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/naps","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"25% stipend reimbursement to employer. ₹1,500/month basic stipend for apprentices."},
  {"name":"Stand Up India Scheme","state":"Central","category":"Business & Finance",
   "slug":"stand-up-india-sc-st-women-loan","officialUrl":"https://standupmitra.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/sui","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹10 lakh – ₹1 crore greenfield enterprise loan for SC/ST and women entrepreneurs."},
  {"name":"PM Shram Yogi Maan-dhan","state":"Central","category":"Labour & Employment",
   "slug":"pm-shram-yogi-maan-dhan-pension-pm-sym","officialUrl":"https://maandhan.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pm-sym","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹3,000/month pension for unorganised workers (₹15,000/month income cap) after age 60."},
  {"name":"NPS for Traders and Self Employed","state":"Central","category":"Labour & Employment",
   "slug":"nps-traders-self-employed-vyapari-scheme","officialUrl":"https://maandhan.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nps-traders","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"₹3,000/month pension for traders/shopkeepers with annual turnover <₹1.5 crore after age 60."},
  {"name":"Rozgar Mela","state":"Central","category":"Labour & Employment",
   "slug":"rozgar-mela-government-job-fair","officialUrl":"https://rozgarmela.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/rm","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Government job fairs with appointment letters given on spot. Freshers can register on portal."},

  # ─── BUSINESS & MSME ──────────────────────────────────────────────
  {"name":"Udyam Registration MSME","state":"Central","category":"Business & Finance",
   "slug":"udyam-registration-msme-online","officialUrl":"https://udyamregistration.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/udyam","priority":1,
   "estimatedMonthlySearches":200000,"langs":["en","hi"],
   "notes":"Free MSME registration for micro/small/medium enterprises. Enables access to all MSME schemes."},
  {"name":"CGTMSE Credit Guarantee Scheme","state":"Central","category":"Business & Finance",
   "slug":"cgtmse-credit-guarantee-scheme-msme-loan","officialUrl":"https://cgtmse.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/cgtmse","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Collateral-free loan guarantee for MSMEs up to ₹5 crore. Covers 75-85% of default."},
  {"name":"GeM Seller Registration","state":"Central","category":"Business & Finance",
   "slug":"gem-government-marketplace-seller-registration","officialUrl":"https://gem.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/gem","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Sell products/services to government online. Zero commission for MSMEs. ₹2 lakh crore annual GMV."},
  {"name":"Zero Defect Zero Effect Scheme","state":"Central","category":"Business & Finance",
   "slug":"zero-defect-zero-effect-zed-msme-certification","officialUrl":"https://zed.msme.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/zed","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"ZED certification for MSMEs for quality and environmental compliance. 80% subsidy on certification."},
  {"name":"SIDBI SMILE Loan","state":"Central","category":"Business & Finance",
   "slug":"sidbi-smile-loan-micro-small-enterprise","officialUrl":"https://www.sidbi.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/sidbi-smile","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Loans ₹10 lakh – ₹25 lakh for micro enterprises at low interest rate via SIDBI."},
  {"name":"Technology Upgradation Fund Scheme TUFS","state":"Central","category":"Business & Finance",
   "slug":"technology-upgradation-fund-scheme-tufs-textile","officialUrl":"https://texmin.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/tufs","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"Interest reimbursement and capital subsidy for modernising textile mills."},

  # ─── SOCIAL SECURITY & WELFARE ────────────────────────────────────
  {"name":"NSAP National Social Assistance Programme","state":"Central","category":"Social Welfare",
   "slug":"nsap-national-social-assistance-old-age-pension","officialUrl":"https://nsap.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nsap","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"Pension for BPL elderly (₹200-500/month), widows (₹300-500/month), disabled persons."},
  {"name":"Indira Gandhi National Old Age Pension","state":"Central","category":"Social Welfare",
   "slug":"indira-gandhi-national-old-age-pension-ignoaps","officialUrl":"https://nsap.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ignoaps","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"₹200/month (60-79 yrs) / ₹500/month (80+) BPL pension under NSAP. State adds on top."},
  {"name":"Indira Gandhi National Widow Pension","state":"Central","category":"Social Welfare",
   "slug":"indira-gandhi-national-widow-pension-ignwps","officialUrl":"https://nsap.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ignwps","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"₹300/month central pension for BPL widows aged 40-79. Most states top up to ₹1,000+."},
  {"name":"Indira Gandhi National Disability Pension","state":"Central","category":"Social Welfare",
   "slug":"indira-gandhi-disability-pension-igndps","officialUrl":"https://nsap.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/igndps","priority":2,
   "estimatedMonthlySearches":25000,"langs":["en","hi"],
   "notes":"₹300/month central pension for BPL persons with 80%+ disability aged 18-79."},
  {"name":"PM Garib Kalyan Ann Yojana","state":"Central","category":"Social Welfare",
   "slug":"pm-garib-kalyan-ann-yojana-free-ration","officialUrl":"https://dfpd.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmgkay","priority":1,
   "estimatedMonthlySearches":300000,"langs":["en","hi"],
   "notes":"5 kg free foodgrains per person per month for NFSA beneficiaries. 80 crore people covered."},
  {"name":"One Nation One Ration Card","state":"Central","category":"Social Welfare",
   "slug":"one-nation-one-ration-card-onorc","officialUrl":"https://impds.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/onorc","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"Portability of ration card across India. Migrants can get ration anywhere in India."},
  {"name":"Antyodaya Anna Yojana","state":"Central","category":"Social Welfare",
   "slug":"antyodaya-anna-yojana-aay-ration-card","officialUrl":"https://dfpd.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/aay","priority":2,
   "estimatedMonthlySearches":40000,"langs":["en","hi"],
   "notes":"35 kg grain/month at ₹2/kg wheat, ₹3/kg rice for poorest of poor families."},
  {"name":"Divyangjan Scholarship","state":"Central","category":"Disability",
   "slug":"divyangjan-scholarship-disabled-students","officialUrl":"https://scholarships.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/dvng-scholar","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Pre/post matric scholarships + free coaching for disabled students. Apply via NSP."},
  {"name":"DPIIT Startup India Seed Fund","state":"Central","category":"Business & Finance",
   "slug":"startup-india-seed-fund-sisfs-incubator","officialUrl":"https://startupindia.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/sisfs","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Up to ₹20 lakh grant + ₹50 lakh soft loan via empanelled incubators for DPIIT startups."},

  # ─── ENERGY & ENVIRONMENT ─────────────────────────────────────────
  {"name":"Saubhagya Scheme Free Electricity","state":"Central","category":"Energy",
   "slug":"saubhagya-scheme-free-electricity-connection","officialUrl":"https://saubhagya.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/saubhagya","priority":2,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Free electricity connection to BPL households. Apply at local electricity office or CSC."},
  {"name":"PAHAL LPG Subsidy DBT","state":"Central","category":"Energy",
   "slug":"pahal-lpg-subsidy-dbt-direct-benefit","officialUrl":"https://mylpg.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pahal","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"LPG subsidy directly credited to bank account (DBT). Link Aadhaar with LPG connection."},
  {"name":"FAME India Scheme EV Subsidy","state":"Central","category":"Energy",
   "slug":"fame-india-scheme-ev-electric-vehicle-subsidy","officialUrl":"https://fame2.heavyindustry.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/fame","priority":2,
   "estimatedMonthlySearches":60000,"langs":["en","hi"],
   "notes":"Electric vehicle purchase subsidy under FAME-II. ₹10,000–1.5 lakh on 2W, 3W, buses, cars."},
  {"name":"National Solar Rooftop Mission","state":"Central","category":"Energy",
   "slug":"national-solar-rooftop-subsidy-residential","officialUrl":"https://solarrooftop.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/nsrm","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"40% subsidy on 1-3 kW solar rooftop systems for homes. Apply via DISCOM or pm surya ghar portal."},

  # ─── HOUSING & URBAN ──────────────────────────────────────────────
  {"name":"Jal Jeevan Mission Har Ghar Jal","state":"Central","category":"Housing",
   "slug":"jal-jeevan-mission-tap-water-connection","officialUrl":"https://jaljeevanmission.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/jjm","priority":2,
   "estimatedMonthlySearches":80000,"langs":["en","hi"],
   "notes":"Tap water connection to every rural household. Apply at gram panchayat."},
  {"name":"Swachh Bharat Mission Gramin","state":"Central","category":"Housing",
   "slug":"swachh-bharat-mission-gramin-toilet-subsidy","officialUrl":"https://swachhbharatmission.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/sbmg","priority":2,
   "estimatedMonthlySearches":50000,"langs":["en","hi"],
   "notes":"₹12,000 incentive for construction of household toilet in rural areas. Apply at gram panchayat."},
  {"name":"PM Gram Sadak Yojana","state":"Central","category":"Infrastructure",
   "slug":"pm-gram-sadak-yojana-rural-road","officialUrl":"https://omms.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmgsy","priority":3,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"All-weather road connectivity for villages with population 250+. Check road status online."},
  {"name":"AMRUT 2.0 Urban Mission","state":"Central","category":"Infrastructure",
   "slug":"amrut-urban-mission-water-sanitation","officialUrl":"https://amrut.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/amrut","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Urban water supply, sewerage, green spaces for cities with 1 lakh+ population."},
  {"name":"Smart Cities Mission","state":"Central","category":"Infrastructure",
   "slug":"smart-cities-mission-india","officialUrl":"https://smartcities.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/scm","priority":3,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"100 smart city projects. Integrated command centres, smart roads, wi-fi, CCTV."},

  # ─── WOMEN & FAMILY ───────────────────────────────────────────────
  {"name":"One Stop Centre Sakhi","state":"Central","category":"Women & Family",
   "slug":"one-stop-centre-sakhi-violence-women","officialUrl":"https://wcd.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/osc","priority":2,
   "estimatedMonthlySearches":20000,"langs":["en","hi"],
   "notes":"Integrated support for women affected by violence. Medical, legal, police, shelter, counselling."},
  {"name":"Working Women Hostel Scheme","state":"Central","category":"Women & Family",
   "slug":"working-women-hostel-scheme-apply","officialUrl":"https://wcd.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/wwhs","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Subsidised hostel accommodation for working women/female students in cities."},
  {"name":"National Creche Scheme","state":"Central","category":"Women & Family",
   "slug":"national-creche-scheme-child-daycare","officialUrl":"https://wcd.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/ncs","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"Day care for children of working mothers (6 months – 6 years). ₹20/day nominal fee."},
  {"name":"Mahila Shakti Kendra","state":"Central","category":"Women & Family",
   "slug":"mahila-shakti-kendra-skill-empowerment","officialUrl":"https://wcd.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/msk","priority":3,
   "estimatedMonthlySearches":10000,"langs":["en","hi"],
   "notes":"Skill training, digital literacy, health awareness for women in block-level centres."},
  {"name":"PM Care Fund","state":"Central","category":"Social Welfare",
   "slug":"pm-care-fund-apply-covid-distress","officialUrl":"https://pmcares.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmcare","priority":3,
   "estimatedMonthlySearches":30000,"langs":["en","hi"],
   "notes":"Emergency relief fund set up for COVID-19. Funds directed to health infra, vaccines, migrants."},

  # ─── DIGITAL & OTHER ──────────────────────────────────────────────
  {"name":"DigiLocker","state":"Central","category":"Digital Services",
   "slug":"digilocker-digital-document-wallet","officialUrl":"https://digilocker.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/digilocker","priority":2,
   "estimatedMonthlySearches":500000,"langs":["en","hi"],
   "notes":"Store driving licence, marksheets, Aadhaar, PAN digitally. Officially valid. 200+ documents."},
  {"name":"UMANG App","state":"Central","category":"Digital Services",
   "slug":"umang-app-government-services","officialUrl":"https://web.umang.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/umang","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"1,700+ government services on one app. PF balance, scholarship, land records, electricity bills."},
  {"name":"Common Service Centre CSC","state":"Central","category":"Digital Services",
   "slug":"common-service-centre-csc-services","officialUrl":"https://csc.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/csc","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"Govt services at village level. Aadhaar enrolment, certificates, banking, insurance at CSC."},
  {"name":"EPFO PF Withdrawal Online","state":"Central","category":"Labour & Employment",
   "slug":"epfo-pf-withdrawal-online-claim","officialUrl":"https://epfindia.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/epfo","priority":1,
   "estimatedMonthlySearches":800000,"langs":["en","hi"],
   "notes":"PF balance check, online withdrawal, UAN activation, pension claim. Very high search volume."},
  {"name":"EPFO EPS Pension","state":"Central","category":"Labour & Employment",
   "slug":"epfo-eps-pension-claim-apply","officialUrl":"https://epfindia.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/eps","priority":2,
   "estimatedMonthlySearches":100000,"langs":["en","hi"],
   "notes":"Employee Pension Scheme. Pension after 10 years of service + 58 years age. Apply on EPFO portal."},
  {"name":"PM WANI WiFi Scheme","state":"Central","category":"Digital Services",
   "slug":"pm-wani-wifi-public-internet-scheme","officialUrl":"https://dot.gov.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/pmwani","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Public Wi-Fi hotspots via local kirana/shops. PM-WANI service providers and PDOA registration."},
  {"name":"BharatNet Rural Broadband","state":"Central","category":"Digital Services",
   "slug":"bharatnet-rural-broadband-scheme","officialUrl":"https://bbnl.nic.in",
   "myschemeUrl":"https://www.myscheme.gov.in/schemes/bharatnet","priority":3,
   "estimatedMonthlySearches":15000,"langs":["en","hi"],
   "notes":"Optical fibre internet to all 2.5 lakh gram panchayats. Free for public Wi-Fi up to 100 Mbps."},
]

existing = {s["slug"] for s in d["schemes"]}
added = [s for s in new_schemes if s["slug"] not in existing]
d["schemes"].extend(added)
f.write_text(json.dumps(d, indent=2, ensure_ascii=False))
print(f"Added {len(added)} schemes. Total: {len(d['schemes'])}")
