/**
 * Generates data/rto/rto.json — all Indian RTO codes
 * Source: Ministry of Road Transport & Highways (MoRTH) / Parivahan portal
 * Run: npx tsx scripts/generate-rto-data.ts
 */

import fs from "fs";
import path from "path";

export interface RTORecord {
  code: string;        // e.g. "MH-04"
  stateCode: string;   // e.g. "MH"
  number: string;      // e.g. "04"
  name: string;        // e.g. "Thane"
  state: string;       // e.g. "Maharashtra"
  stateSlug: string;
  city: string;        // primary city for this RTO
  slug: string;        // e.g. "mh-04"
}

function slugify(t: string) {
  return t.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

// Comprehensive RTO list — MoRTH Parivahan data
const RTO_RAW: [string, string, string, string][] = [
  // [stateCode, number, rtoName, stateName]
  // Andhra Pradesh
  ["AP","01","Vijayawada (Central)","Andhra Pradesh"],
  ["AP","02","Vijayawada (West)","Andhra Pradesh"],
  ["AP","03","Guntur","Andhra Pradesh"],
  ["AP","04","Nellore","Andhra Pradesh"],
  ["AP","05","Kurnool","Andhra Pradesh"],
  ["AP","06","Kadapa","Andhra Pradesh"],
  ["AP","07","Anantapur","Andhra Pradesh"],
  ["AP","08","Chittoor","Andhra Pradesh"],
  ["AP","09","Ongole","Andhra Pradesh"],
  ["AP","10","Eluru","Andhra Pradesh"],
  ["AP","11","Rajamahendravaram","Andhra Pradesh"],
  ["AP","12","Visakhapatnam","Andhra Pradesh"],
  ["AP","13","Srikakulam","Andhra Pradesh"],
  ["AP","14","Vizianagaram","Andhra Pradesh"],
  ["AP","15","Tirupati","Andhra Pradesh"],
  ["AP","16","Nandyal","Andhra Pradesh"],
  ["AP","39","Amaravati","Andhra Pradesh"],

  // Arunachal Pradesh
  ["AR","01","Itanagar","Arunachal Pradesh"],
  ["AR","02","Naharlagun","Arunachal Pradesh"],
  ["AR","03","Pasighat","Arunachal Pradesh"],

  // Assam
  ["AS","01","Guwahati","Assam"],
  ["AS","02","Dibrugarh","Assam"],
  ["AS","03","Jorhat","Assam"],
  ["AS","04","Silchar","Assam"],
  ["AS","05","Tezpur","Assam"],
  ["AS","06","Bongaigaon","Assam"],
  ["AS","07","Dhubri","Assam"],
  ["AS","08","Nagaon","Assam"],
  ["AS","09","Goalpara","Assam"],
  ["AS","10","Diphu","Assam"],
  ["AS","11","Nalbari","Assam"],
  ["AS","12","Karimganj","Assam"],
  ["AS","13","North Lakhimpur","Assam"],
  ["AS","14","Sivasagar","Assam"],
  ["AS","15","Kokrajhar","Assam"],
  ["AS","16","Hailakandi","Assam"],
  ["AS","17","Golaghat","Assam"],
  ["AS","18","Morigaon","Assam"],
  ["AS","23","Barpeta","Assam"],

  // Bihar
  ["BR","01","Patna","Bihar"],
  ["BR","02","Gaya","Bihar"],
  ["BR","03","Bhagalpur","Bihar"],
  ["BR","04","Muzaffarpur","Bihar"],
  ["BR","05","Darbhanga","Bihar"],
  ["BR","06","Chapra","Bihar"],
  ["BR","07","Hajipur","Bihar"],
  ["BR","08","Purnia","Bihar"],
  ["BR","09","Samastipur","Bihar"],
  ["BR","10","Sitamarhi","Bihar"],
  ["BR","11","Arrah","Bihar"],
  ["BR","12","Biharsharif","Bihar"],
  ["BR","13","Aurangabad","Bihar"],
  ["BR","14","Begusarai","Bihar"],
  ["BR","15","Madhubani","Bihar"],
  ["BR","16","Supaul","Bihar"],
  ["BR","17","Sasaram","Bihar"],
  ["BR","18","Buxar","Bihar"],
  ["BR","19","Siwan","Bihar"],
  ["BR","20","Gopalganj","Bihar"],
  ["BR","21","Motihari","Bihar"],
  ["BR","22","Katihar","Bihar"],
  ["BR","23","Munger","Bihar"],
  ["BR","24","Kishanganj","Bihar"],
  ["BR","25","Madhepura","Bihar"],
  ["BR","26","Araria","Bihar"],
  ["BR","27","Sheikhpura","Bihar"],
  ["BR","38","Nalanda","Bihar"],
  ["BR","43","Jehanabad","Bihar"],
  ["BR","44","Lakhisarai","Bihar"],
  ["BR","45","Jamui","Bihar"],
  ["BR","46","Khagaria","Bihar"],
  ["BR","47","Sheohar","Bihar"],

  // Chhattisgarh
  ["CG","01","Raipur","Chhattisgarh"],
  ["CG","02","Durg","Chhattisgarh"],
  ["CG","03","Bilaspur","Chhattisgarh"],
  ["CG","04","Jagdalpur","Chhattisgarh"],
  ["CG","05","Rajnandgaon","Chhattisgarh"],
  ["CG","06","Ambikapur","Chhattisgarh"],
  ["CG","07","Kanker","Chhattisgarh"],
  ["CG","08","Korba","Chhattisgarh"],
  ["CG","09","Raigarh","Chhattisgarh"],
  ["CG","10","Janjgir","Chhattisgarh"],
  ["CG","11","Mahasamund","Chhattisgarh"],
  ["CG","12","Dhamtari","Chhattisgarh"],

  // Goa
  ["GA","01","Panaji","Goa"],
  ["GA","02","Margao","Goa"],
  ["GA","03","Mapusa","Goa"],
  ["GA","04","Vasco","Goa"],
  ["GA","05","Ponda","Goa"],
  ["GA","06","Bicholim","Goa"],

  // Gujarat
  ["GJ","01","Ahmedabad (East)","Gujarat"],
  ["GJ","02","Ahmedabad (West)","Gujarat"],
  ["GJ","03","Rajkot","Gujarat"],
  ["GJ","04","Surat","Gujarat"],
  ["GJ","05","Vadodara","Gujarat"],
  ["GJ","06","Bhavnagar","Gujarat"],
  ["GJ","07","Jamnagar","Gujarat"],
  ["GJ","08","Junagadh","Gujarat"],
  ["GJ","09","Mehsana","Gujarat"],
  ["GJ","10","Gandhinagar","Gujarat"],
  ["GJ","11","Anand","Gujarat"],
  ["GJ","12","Navsari","Gujarat"],
  ["GJ","13","Valsad","Gujarat"],
  ["GJ","14","Amreli","Gujarat"],
  ["GJ","15","Palanpur","Gujarat"],
  ["GJ","16","Himatnagar","Gujarat"],
  ["GJ","17","Surendranagar","Gujarat"],
  ["GJ","18","Godhra","Gujarat"],
  ["GJ","19","Bharuch","Gujarat"],
  ["GJ","20","Botad","Gujarat"],
  ["GJ","21","Dahod","Gujarat"],
  ["GJ","22","Morbi","Gujarat"],
  ["GJ","23","Diu","Gujarat"],
  ["GJ","24","Porbandar","Gujarat"],
  ["GJ","25","Veraval","Gujarat"],
  ["GJ","27","Narmada","Gujarat"],
  ["GJ","28","Tapi","Gujarat"],
  ["GJ","29","Vapi","Gujarat"],
  ["GJ","33","Ahmedabad (North)","Gujarat"],
  ["GJ","34","Surat (West)","Gujarat"],

  // Haryana
  ["HR","01","Ambala","Haryana"],
  ["HR","02","Hisar","Haryana"],
  ["HR","03","Rohtak","Haryana"],
  ["HR","04","Gurgaon","Haryana"],
  ["HR","05","Faridabad","Haryana"],
  ["HR","06","Bhiwani","Haryana"],
  ["HR","07","Karnal","Haryana"],
  ["HR","08","Kurukshetra","Haryana"],
  ["HR","09","Sonipat","Haryana"],
  ["HR","10","Panipat","Haryana"],
  ["HR","11","Mahendragarh","Haryana"],
  ["HR","12","Jind","Haryana"],
  ["HR","13","Yamuna Nagar","Haryana"],
  ["HR","14","Sirsa","Haryana"],
  ["HR","15","Rewari","Haryana"],
  ["HR","16","Panchkula","Haryana"],
  ["HR","17","Jhajjar","Haryana"],
  ["HR","18","Kaithal","Haryana"],
  ["HR","19","Palwal","Haryana"],
  ["HR","20","Mewat","Haryana"],
  ["HR","21","Fatehabad","Haryana"],
  ["HR","26","Manesar","Haryana"],
  ["HR","55","Bahadurgarh","Haryana"],

  // Himachal Pradesh
  ["HP","01","Shimla","Himachal Pradesh"],
  ["HP","02","Mandi","Himachal Pradesh"],
  ["HP","03","Dharamshala","Himachal Pradesh"],
  ["HP","04","Solan","Himachal Pradesh"],
  ["HP","05","Hamirpur","Himachal Pradesh"],
  ["HP","06","Kullu","Himachal Pradesh"],
  ["HP","07","Una","Himachal Pradesh"],
  ["HP","08","Bilaspur","Himachal Pradesh"],
  ["HP","09","Chamba","Himachal Pradesh"],
  ["HP","10","Kinnaur","Himachal Pradesh"],
  ["HP","11","Lahaul & Spiti","Himachal Pradesh"],
  ["HP","12","Sirmaur","Himachal Pradesh"],

  // Jammu & Kashmir
  ["JK","01","Jammu","Jammu & Kashmir"],
  ["JK","02","Srinagar","Jammu & Kashmir"],
  ["JK","03","Anantnag","Jammu & Kashmir"],
  ["JK","04","Baramulla","Jammu & Kashmir"],
  ["JK","05","Udhampur","Jammu & Kashmir"],
  ["JK","06","Kathua","Jammu & Kashmir"],
  ["JK","07","Sopore","Jammu & Kashmir"],
  ["JK","08","Rajouri","Jammu & Kashmir"],
  ["JK","09","Poonch","Jammu & Kashmir"],
  ["JK","10","Kargil","Jammu & Kashmir"],
  ["JK","11","Leh","Jammu & Kashmir"],

  // Jharkhand
  ["JH","01","Ranchi","Jharkhand"],
  ["JH","02","Jamshedpur","Jharkhand"],
  ["JH","03","Dhanbad","Jharkhand"],
  ["JH","04","Bokaro","Jharkhand"],
  ["JH","05","Hazaribagh","Jharkhand"],
  ["JH","06","Giridih","Jharkhand"],
  ["JH","07","Deoghar","Jharkhand"],
  ["JH","08","Dumka","Jharkhand"],
  ["JH","09","Chaibasa","Jharkhand"],
  ["JH","10","Garhwa","Jharkhand"],
  ["JH","11","Palamu","Jharkhand"],
  ["JH","12","Lohardaga","Jharkhand"],
  ["JH","13","Gumla","Jharkhand"],
  ["JH","14","Sahebganj","Jharkhand"],
  ["JH","15","Pakur","Jharkhand"],
  ["JH","16","Godda","Jharkhand"],
  ["JH","17","Koderma","Jharkhand"],
  ["JH","18","Chatra","Jharkhand"],
  ["JH","19","Simdega","Jharkhand"],
  ["JH","20","Khunti","Jharkhand"],

  // Karnataka
  ["KA","01","Bengaluru (Central)","Karnataka"],
  ["KA","02","Bengaluru (West)","Karnataka"],
  ["KA","03","Tumkur","Karnataka"],
  ["KA","04","Kolar","Karnataka"],
  ["KA","05","Mandya","Karnataka"],
  ["KA","06","Mysuru","Karnataka"],
  ["KA","07","Hassan","Karnataka"],
  ["KA","08","Mangaluru","Karnataka"],
  ["KA","09","Udupi","Karnataka"],
  ["KA","10","Uttara Kannada","Karnataka"],
  ["KA","11","Dharwad","Karnataka"],
  ["KA","12","Gadag","Karnataka"],
  ["KA","13","Haveri","Karnataka"],
  ["KA","14","Belagavi","Karnataka"],
  ["KA","15","Vijayapura","Karnataka"],
  ["KA","16","Bagalkot","Karnataka"],
  ["KA","17","Ballari","Karnataka"],
  ["KA","18","Raichur","Karnataka"],
  ["KA","19","Koppal","Karnataka"],
  ["KA","20","Gulbarga (Kalaburagi)","Karnataka"],
  ["KA","21","Bidar","Karnataka"],
  ["KA","22","Yadgir","Karnataka"],
  ["KA","23","Chitradurga","Karnataka"],
  ["KA","24","Davanagere","Karnataka"],
  ["KA","25","Chikkamagaluru","Karnataka"],
  ["KA","26","Shivamogga","Karnataka"],
  ["KA","27","Kodagu","Karnataka"],
  ["KA","28","Chikkaballapur","Karnataka"],
  ["KA","29","Ramanagara","Karnataka"],
  ["KA","41","Bengaluru (East)","Karnataka"],
  ["KA","50","Bengaluru (North)","Karnataka"],
  ["KA","51","Bengaluru (South)","Karnataka"],
  ["KA","57","Anekal","Karnataka"],

  // Kerala
  ["KL","01","Thiruvananthapuram","Kerala"],
  ["KL","02","Kollam","Kerala"],
  ["KL","03","Alappuzha","Kerala"],
  ["KL","04","Pathanamthitta","Kerala"],
  ["KL","05","Kottayam","Kerala"],
  ["KL","06","Ernakulam","Kerala"],
  ["KL","07","Idukki","Kerala"],
  ["KL","08","Thrissur","Kerala"],
  ["KL","09","Palakkad","Kerala"],
  ["KL","10","Malappuram","Kerala"],
  ["KL","11","Kozhikode","Kerala"],
  ["KL","12","Wayanad","Kerala"],
  ["KL","13","Kannur","Kerala"],
  ["KL","14","Kasaragod","Kerala"],
  ["KL","15","Perinthalmanna","Kerala"],
  ["KL","39","Kochi (City)","Kerala"],
  ["KL","43","Kalamassery","Kerala"],
  ["KL","57","Kothamangalam","Kerala"],
  ["KL","58","Muvattupuzha","Kerala"],

  // Madhya Pradesh
  ["MP","01","Bhopal","Madhya Pradesh"],
  ["MP","02","Indore","Madhya Pradesh"],
  ["MP","03","Gwalior","Madhya Pradesh"],
  ["MP","04","Jabalpur","Madhya Pradesh"],
  ["MP","05","Ujjain","Madhya Pradesh"],
  ["MP","06","Sagar","Madhya Pradesh"],
  ["MP","07","Rewa","Madhya Pradesh"],
  ["MP","08","Satna","Madhya Pradesh"],
  ["MP","09","Chhindwara","Madhya Pradesh"],
  ["MP","10","Hoshangabad","Madhya Pradesh"],
  ["MP","11","Dewas","Madhya Pradesh"],
  ["MP","12","Khandwa","Madhya Pradesh"],
  ["MP","13","Khargone","Madhya Pradesh"],
  ["MP","14","Mandsaur","Madhya Pradesh"],
  ["MP","15","Ratlam","Madhya Pradesh"],
  ["MP","16","Shivpuri","Madhya Pradesh"],
  ["MP","17","Morena","Madhya Pradesh"],
  ["MP","18","Bhind","Madhya Pradesh"],
  ["MP","19","Sehore","Madhya Pradesh"],
  ["MP","20","Raisen","Madhya Pradesh"],
  ["MP","21","Vidisha","Madhya Pradesh"],
  ["MP","22","Shajapur","Madhya Pradesh"],
  ["MP","23","Tikamgarh","Madhya Pradesh"],
  ["MP","24","Chhatarpur","Madhya Pradesh"],
  ["MP","25","Damoh","Madhya Pradesh"],
  ["MP","26","Panna","Madhya Pradesh"],
  ["MP","27","Shahdol","Madhya Pradesh"],
  ["MP","28","Seoni","Madhya Pradesh"],
  ["MP","29","Balaghat","Madhya Pradesh"],
  ["MP","30","Narsinghpur","Madhya Pradesh"],
  ["MP","31","Mandla","Madhya Pradesh"],
  ["MP","32","Dindori","Madhya Pradesh"],
  ["MP","33","Betul","Madhya Pradesh"],
  ["MP","34","Harda","Madhya Pradesh"],
  ["MP","35","Barwani","Madhya Pradesh"],
  ["MP","36","Alirajpur","Madhya Pradesh"],
  ["MP","37","Burhanpur","Madhya Pradesh"],
  ["MP","38","Anuppur","Madhya Pradesh"],
  ["MP","39","Umaria","Madhya Pradesh"],
  ["MP","40","Sidhi","Madhya Pradesh"],
  ["MP","41","Singrauli","Madhya Pradesh"],
  ["MP","43","Agar-Malwa","Madhya Pradesh"],
  ["MP","44","Niwari","Madhya Pradesh"],

  // Maharashtra
  ["MH","01","Mumbai (Central)","Maharashtra"],
  ["MH","02","Mumbai (West)","Maharashtra"],
  ["MH","03","Mumbai (East)","Maharashtra"],
  ["MH","04","Thane","Maharashtra"],
  ["MH","05","Kalyan","Maharashtra"],
  ["MH","06","Raigad","Maharashtra"],
  ["MH","07","Pune","Maharashtra"],
  ["MH","08","Nashik","Maharashtra"],
  ["MH","09","Ahmadnagar","Maharashtra"],
  ["MH","10","Kolhapur","Maharashtra"],
  ["MH","11","Sangli","Maharashtra"],
  ["MH","12","Satara","Maharashtra"],
  ["MH","13","Solapur","Maharashtra"],
  ["MH","14","Aurangabad","Maharashtra"],
  ["MH","15","Jalna","Maharashtra"],
  ["MH","16","Beed","Maharashtra"],
  ["MH","17","Latur","Maharashtra"],
  ["MH","18","Osmanabad","Maharashtra"],
  ["MH","19","Nanded","Maharashtra"],
  ["MH","20","Parbhani","Maharashtra"],
  ["MH","21","Hingoli","Maharashtra"],
  ["MH","22","Dhule","Maharashtra"],
  ["MH","23","Nandurbar","Maharashtra"],
  ["MH","24","Jalgaon","Maharashtra"],
  ["MH","25","Amravati","Maharashtra"],
  ["MH","26","Nagpur","Maharashtra"],
  ["MH","27","Wardha","Maharashtra"],
  ["MH","28","Yavatmal","Maharashtra"],
  ["MH","29","Nandurbar","Maharashtra"],
  ["MH","30","Gondia","Maharashtra"],
  ["MH","31","Chandrapur","Maharashtra"],
  ["MH","32","Bhandara","Maharashtra"],
  ["MH","33","Gadchiroli","Maharashtra"],
  ["MH","34","Ratnagiri","Maharashtra"],
  ["MH","35","Sindhudurg","Maharashtra"],
  ["MH","36","Buldhana","Maharashtra"],
  ["MH","37","Akola","Maharashtra"],
  ["MH","38","Washim","Maharashtra"],
  ["MH","43","Pimpri-Chinchwad","Maharashtra"],
  ["MH","46","Navi Mumbai","Maharashtra"],
  ["MH","47","Mira-Bhayander","Maharashtra"],
  ["MH","48","Vasai-Virar","Maharashtra"],
  ["MH","49","Bhiwandi","Maharashtra"],
  ["MH","50","Panvel","Maharashtra"],

  // Manipur
  ["MN","01","Imphal","Manipur"],
  ["MN","02","Thoubal","Manipur"],
  ["MN","03","Bishnupur","Manipur"],
  ["MN","04","Churachandpur","Manipur"],
  ["MN","05","Senapati","Manipur"],

  // Meghalaya
  ["ML","01","Shillong","Meghalaya"],
  ["ML","02","Tura","Meghalaya"],
  ["ML","03","Jowai","Meghalaya"],

  // Mizoram
  ["MZ","01","Aizawl","Mizoram"],
  ["MZ","02","Lunglei","Mizoram"],

  // Nagaland
  ["NL","01","Kohima","Nagaland"],
  ["NL","02","Dimapur","Nagaland"],
  ["NL","03","Mokokchung","Nagaland"],
  ["NL","04","Tuensang","Nagaland"],

  // Odisha
  ["OD","01","Bhubaneswar","Odisha"],
  ["OD","02","Cuttack","Odisha"],
  ["OD","03","Berhampur","Odisha"],
  ["OD","04","Sambalpur","Odisha"],
  ["OD","05","Rourkela","Odisha"],
  ["OD","06","Balasore","Odisha"],
  ["OD","07","Baripada","Odisha"],
  ["OD","08","Dhenkanal","Odisha"],
  ["OD","09","Bolangir","Odisha"],
  ["OD","10","Koraput","Odisha"],
  ["OD","11","Phulbani","Odisha"],
  ["OD","12","Sonepur","Odisha"],
  ["OD","13","Keonjhar","Odisha"],
  ["OD","14","Sundargarh","Odisha"],
  ["OD","15","Bhadrak","Odisha"],
  ["OD","16","Kendrapara","Odisha"],
  ["OD","17","Jagatsinghpur","Odisha"],
  ["OD","18","Jajpur","Odisha"],
  ["OD","19","Angul","Odisha"],
  ["OD","20","Nayagarh","Odisha"],
  ["OD","21","Khurda","Odisha"],
  ["OD","22","Ganjam","Odisha"],
  ["OD","23","Puri","Odisha"],
  ["OD","24","Nuapada","Odisha"],
  ["OD","25","Nawapara","Odisha"],
  ["OD","26","Malkangiri","Odisha"],
  ["OD","27","Nabarangapur","Odisha"],
  ["OD","28","Rayagada","Odisha"],
  ["OD","29","Bargarh","Odisha"],
  ["OD","30","Debagarh","Odisha"],
  ["OD","31","Jharsuguda","Odisha"],
  ["OD","32","Subarnapur","Odisha"],

  // Punjab
  ["PB","01","Amritsar","Punjab"],
  ["PB","02","Jalandhar","Punjab"],
  ["PB","03","Patiala","Punjab"],
  ["PB","04","Ludhiana","Punjab"],
  ["PB","05","Bathinda","Punjab"],
  ["PB","06","Gurdaspur","Punjab"],
  ["PB","07","Hoshiarpur","Punjab"],
  ["PB","08","Ropar","Punjab"],
  ["PB","09","Sangrur","Punjab"],
  ["PB","10","Firozpur","Punjab"],
  ["PB","11","Fazilka","Punjab"],
  ["PB","12","Faridkot","Punjab"],
  ["PB","13","Muktsar","Punjab"],
  ["PB","14","Moga","Punjab"],
  ["PB","15","Kapurthala","Punjab"],
  ["PB","16","Nawanshahr","Punjab"],
  ["PB","17","Pathankot","Punjab"],
  ["PB","19","Mohali","Punjab"],
  ["PB","20","Fatehgarh Sahib","Punjab"],
  ["PB","21","Tarn Taran","Punjab"],
  ["PB","24","Barnala","Punjab"],
  ["PB","65","Ludhiana (Rural)","Punjab"],

  // Rajasthan
  ["RJ","01","Jaipur","Rajasthan"],
  ["RJ","02","Ajmer","Rajasthan"],
  ["RJ","03","Alwar","Rajasthan"],
  ["RJ","04","Bharatpur","Rajasthan"],
  ["RJ","05","Bikaner","Rajasthan"],
  ["RJ","06","Bundi","Rajasthan"],
  ["RJ","07","Chittorgarh","Rajasthan"],
  ["RJ","08","Churu","Rajasthan"],
  ["RJ","09","Dausa","Rajasthan"],
  ["RJ","10","Dhaulpur","Rajasthan"],
  ["RJ","11","Dungarpur","Rajasthan"],
  ["RJ","12","Ganganagar","Rajasthan"],
  ["RJ","13","Hanumangarh","Rajasthan"],
  ["RJ","14","Jaisalmer","Rajasthan"],
  ["RJ","15","Jalore","Rajasthan"],
  ["RJ","16","Jhalawar","Rajasthan"],
  ["RJ","17","Jhunjhunu","Rajasthan"],
  ["RJ","18","Jodhpur","Rajasthan"],
  ["RJ","19","Karauli","Rajasthan"],
  ["RJ","20","Kota","Rajasthan"],
  ["RJ","21","Nagaur","Rajasthan"],
  ["RJ","22","Pali","Rajasthan"],
  ["RJ","23","Rajsamand","Rajasthan"],
  ["RJ","24","Sawai Madhopur","Rajasthan"],
  ["RJ","25","Sikar","Rajasthan"],
  ["RJ","26","Sirohi","Rajasthan"],
  ["RJ","27","Tonk","Rajasthan"],
  ["RJ","28","Udaipur","Rajasthan"],
  ["RJ","29","Banswara","Rajasthan"],
  ["RJ","30","Barmer","Rajasthan"],
  ["RJ","31","Baran","Rajasthan"],
  ["RJ","45","Jaipur (Rural)","Rajasthan"],
  ["RJ","46","Jodhpur (Rural)","Rajasthan"],

  // Sikkim
  ["SK","01","Gangtok","Sikkim"],
  ["SK","02","Namchi","Sikkim"],

  // Tamil Nadu
  ["TN","01","Chennai (Central)","Tamil Nadu"],
  ["TN","02","Chennai (North)","Tamil Nadu"],
  ["TN","03","Chennai (South)","Tamil Nadu"],
  ["TN","04","Vellore","Tamil Nadu"],
  ["TN","05","Dharmapuri","Tamil Nadu"],
  ["TN","06","Salem","Tamil Nadu"],
  ["TN","07","Namakkal","Tamil Nadu"],
  ["TN","08","Erode","Tamil Nadu"],
  ["TN","09","Coimbatore","Tamil Nadu"],
  ["TN","10","Nilgiris","Tamil Nadu"],
  ["TN","11","Tirupur","Tamil Nadu"],
  ["TN","12","Karur","Tamil Nadu"],
  ["TN","13","Tiruchirappalli","Tamil Nadu"],
  ["TN","14","Thanjavur","Tamil Nadu"],
  ["TN","15","Nagapattinam","Tamil Nadu"],
  ["TN","16","Pudukkottai","Tamil Nadu"],
  ["TN","17","Madurai","Tamil Nadu"],
  ["TN","18","Dindigul","Tamil Nadu"],
  ["TN","19","Ramanathapuram","Tamil Nadu"],
  ["TN","20","Virudhunagar","Tamil Nadu"],
  ["TN","21","Tirunelveli","Tamil Nadu"],
  ["TN","22","Thoothukudi","Tamil Nadu"],
  ["TN","23","Kanyakumari","Tamil Nadu"],
  ["TN","24","Cuddalore","Tamil Nadu"],
  ["TN","25","Villupuram","Tamil Nadu"],
  ["TN","26","Tiruvannamalai","Tamil Nadu"],
  ["TN","27","Perambalur","Tamil Nadu"],
  ["TN","28","Ariyalur","Tamil Nadu"],
  ["TN","29","Sivagangai","Tamil Nadu"],
  ["TN","30","Tiruvarur","Tamil Nadu"],
  ["TN","31","Krishnagiri","Tamil Nadu"],
  ["TN","32","Kancheepuram","Tamil Nadu"],
  ["TN","33","Tiruvallur","Tamil Nadu"],
  ["TN","38","Chennai (West)","Tamil Nadu"],
  ["TN","45","Theni","Tamil Nadu"],
  ["TN","56","Kallakurichi","Tamil Nadu"],
  ["TN","57","Ranipet","Tamil Nadu"],
  ["TN","58","Tenkasi","Tamil Nadu"],
  ["TN","59","Chengalpattu","Tamil Nadu"],

  // Telangana
  ["TS","01","Hyderabad (Central)","Telangana"],
  ["TS","02","Hyderabad (West)","Telangana"],
  ["TS","03","Ranga Reddy","Telangana"],
  ["TS","04","Medak","Telangana"],
  ["TS","05","Nizamabad","Telangana"],
  ["TS","06","Adilabad","Telangana"],
  ["TS","07","Karimnagar","Telangana"],
  ["TS","08","Warangal","Telangana"],
  ["TS","09","Khammam","Telangana"],
  ["TS","10","Nalgonda","Telangana"],
  ["TS","11","Mahbubnagar","Telangana"],
  ["TS","12","Siddipet","Telangana"],
  ["TS","13","Sangareddy","Telangana"],
  ["TS","14","Yadadri","Telangana"],
  ["TS","15","Suryapet","Telangana"],
  ["TS","16","Mancherial","Telangana"],
  ["TS","17","Peddapalli","Telangana"],
  ["TS","18","Jagitial","Telangana"],
  ["TS","19","Rajanna Sircilla","Telangana"],
  ["TS","20","Nirmal","Telangana"],
  ["TS","21","Kumuram Bheem","Telangana"],
  ["TS","22","Mulugu","Telangana"],
  ["TS","23","Bhadradri","Telangana"],
  ["TS","24","Jayashankar","Telangana"],
  ["TS","25","Narayanpet","Telangana"],
  ["TS","26","Vikarabad","Telangana"],
  ["TS","27","Medchal","Telangana"],
  ["TS","29","Hyderabad (East)","Telangana"],
  ["TS","30","Cyberabad","Telangana"],

  // Tripura
  ["TR","01","Agartala","Tripura"],
  ["TR","02","Dharmanagar","Tripura"],
  ["TR","03","Udaipur","Tripura"],
  ["TR","04","Belonia","Tripura"],

  // Uttar Pradesh
  ["UP","11","Agra","Uttar Pradesh"],
  ["UP","12","Aligarh","Uttar Pradesh"],
  ["UP","13","Allahabad (Prayagraj)","Uttar Pradesh"],
  ["UP","14","Ambedkar Nagar","Uttar Pradesh"],
  ["UP","15","Amethi","Uttar Pradesh"],
  ["UP","16","Amroha","Uttar Pradesh"],
  ["UP","17","Auraiya","Uttar Pradesh"],
  ["UP","18","Azamgarh","Uttar Pradesh"],
  ["UP","19","Baghpat","Uttar Pradesh"],
  ["UP","20","Bahraich","Uttar Pradesh"],
  ["UP","21","Ballia","Uttar Pradesh"],
  ["UP","22","Balrampur","Uttar Pradesh"],
  ["UP","23","Banda","Uttar Pradesh"],
  ["UP","24","Barabanki","Uttar Pradesh"],
  ["UP","25","Bareilly","Uttar Pradesh"],
  ["UP","26","Basti","Uttar Pradesh"],
  ["UP","27","Bijnor","Uttar Pradesh"],
  ["UP","28","Budaun","Uttar Pradesh"],
  ["UP","29","Bulandshahr","Uttar Pradesh"],
  ["UP","30","Chandauli","Uttar Pradesh"],
  ["UP","31","Chitrakoot","Uttar Pradesh"],
  ["UP","32","Deoria","Uttar Pradesh"],
  ["UP","33","Etah","Uttar Pradesh"],
  ["UP","34","Etawah","Uttar Pradesh"],
  ["UP","35","Faizabad (Ayodhya)","Uttar Pradesh"],
  ["UP","36","Farrukhabad","Uttar Pradesh"],
  ["UP","37","Fatehpur","Uttar Pradesh"],
  ["UP","38","Firozabad","Uttar Pradesh"],
  ["UP","39","Gautam Buddha Nagar (Noida)","Uttar Pradesh"],
  ["UP","40","Ghaziabad","Uttar Pradesh"],
  ["UP","41","Ghazipur","Uttar Pradesh"],
  ["UP","42","Gonda","Uttar Pradesh"],
  ["UP","43","Gorakhpur","Uttar Pradesh"],
  ["UP","44","Hamirpur","Uttar Pradesh"],
  ["UP","45","Hapur","Uttar Pradesh"],
  ["UP","46","Hardoi","Uttar Pradesh"],
  ["UP","47","Hathras","Uttar Pradesh"],
  ["UP","48","Jalaun","Uttar Pradesh"],
  ["UP","49","Jaunpur","Uttar Pradesh"],
  ["UP","50","Jhansi","Uttar Pradesh"],
  ["UP","51","Kannauj","Uttar Pradesh"],
  ["UP","52","Kanpur (City)","Uttar Pradesh"],
  ["UP","53","Kanpur Dehat","Uttar Pradesh"],
  ["UP","54","Kasganj","Uttar Pradesh"],
  ["UP","55","Kaushambi","Uttar Pradesh"],
  ["UP","56","Kheri","Uttar Pradesh"],
  ["UP","57","Kushinagar","Uttar Pradesh"],
  ["UP","58","Lalitpur","Uttar Pradesh"],
  ["UP","59","Lucknow","Uttar Pradesh"],
  ["UP","60","Maharajganj","Uttar Pradesh"],
  ["UP","61","Mahoba","Uttar Pradesh"],
  ["UP","62","Mainpuri","Uttar Pradesh"],
  ["UP","63","Mathura","Uttar Pradesh"],
  ["UP","64","Mau","Uttar Pradesh"],
  ["UP","65","Meerut","Uttar Pradesh"],
  ["UP","66","Mirzapur","Uttar Pradesh"],
  ["UP","67","Moradabad","Uttar Pradesh"],
  ["UP","68","Muzaffarnagar","Uttar Pradesh"],
  ["UP","69","Pilibhit","Uttar Pradesh"],
  ["UP","70","Pratapgarh","Uttar Pradesh"],
  ["UP","71","Raebareli","Uttar Pradesh"],
  ["UP","72","Rampur","Uttar Pradesh"],
  ["UP","73","Saharanpur","Uttar Pradesh"],
  ["UP","74","Sambhal","Uttar Pradesh"],
  ["UP","75","Sant Kabir Nagar","Uttar Pradesh"],
  ["UP","76","Sant Ravidas Nagar","Uttar Pradesh"],
  ["UP","77","Shahjahanpur","Uttar Pradesh"],
  ["UP","78","Shamli","Uttar Pradesh"],
  ["UP","79","Shrawasti","Uttar Pradesh"],
  ["UP","80","Siddharthnagar","Uttar Pradesh"],
  ["UP","81","Sitapur","Uttar Pradesh"],
  ["UP","82","Sonbhadra","Uttar Pradesh"],
  ["UP","83","Sultanpur","Uttar Pradesh"],
  ["UP","84","Unnao","Uttar Pradesh"],
  ["UP","85","Varanasi","Uttar Pradesh"],

  // Uttarakhand
  ["UK","01","Dehradun","Uttarakhand"],
  ["UK","02","Haridwar","Uttarakhand"],
  ["UK","03","Rishikesh","Uttarakhand"],
  ["UK","04","Roorkee","Uttarakhand"],
  ["UK","05","Nainital","Uttarakhand"],
  ["UK","06","Almora","Uttarakhand"],
  ["UK","07","Pauri Garhwal","Uttarakhand"],
  ["UK","08","Tehri Garhwal","Uttarakhand"],
  ["UK","09","Uttarkashi","Uttarakhand"],
  ["UK","10","Chamoli","Uttarakhand"],
  ["UK","11","Rudraprayag","Uttarakhand"],
  ["UK","12","Champawat","Uttarakhand"],
  ["UK","13","Pithoragarh","Uttarakhand"],
  ["UK","14","Bageshwar","Uttarakhand"],
  ["UK","15","Udham Singh Nagar","Uttarakhand"],
  ["UK","16","Haldwani","Uttarakhand"],

  // West Bengal
  ["WB","01","Kolkata","West Bengal"],
  ["WB","02","Howrah","West Bengal"],
  ["WB","03","Hooghly","West Bengal"],
  ["WB","04","24 Parganas (North)","West Bengal"],
  ["WB","05","24 Parganas (South)","West Bengal"],
  ["WB","06","Nadia","West Bengal"],
  ["WB","07","Murshidabad","West Bengal"],
  ["WB","08","Birbhum","West Bengal"],
  ["WB","09","Burdwan","West Bengal"],
  ["WB","10","Bankura","West Bengal"],
  ["WB","11","Purulia","West Bengal"],
  ["WB","12","Midnapore (West)","West Bengal"],
  ["WB","13","Midnapore (East)","West Bengal"],
  ["WB","14","Jhargram","West Bengal"],
  ["WB","15","Malda","West Bengal"],
  ["WB","16","Dinajpur (North)","West Bengal"],
  ["WB","17","Dinajpur (South)","West Bengal"],
  ["WB","18","Jalpaiguri","West Bengal"],
  ["WB","19","Cooch Behar","West Bengal"],
  ["WB","20","Darjeeling","West Bengal"],
  ["WB","21","Kalimpong","West Bengal"],
  ["WB","22","Alipurduar","West Bengal"],
  ["WB","23","Siliguri","West Bengal"],
  ["WB","24","Asansol","West Bengal"],
  ["WB","25","Durgapur","West Bengal"],
  ["WB","26","Barasat","West Bengal"],
  ["WB","27","Barrackpore","West Bengal"],

  // Union Territories
  ["AN","01","Port Blair","Andaman & Nicobar Islands"],
  ["CH","01","Chandigarh","Chandigarh"],
  ["DD","01","Daman","Daman & Diu"],
  ["DD","02","Diu","Daman & Diu"],
  ["DN","01","Silvassa","Dadra & Nagar Haveli"],
  ["DL","01","Delhi (Central)","Delhi"],
  ["DL","02","Delhi (West)","Delhi"],
  ["DL","03","Delhi (North)","Delhi"],
  ["DL","04","Delhi (South)","Delhi"],
  ["DL","05","Delhi (East)","Delhi"],
  ["DL","06","Delhi (Shahdara)","Delhi"],
  ["DL","07","Delhi (South West)","Delhi"],
  ["DL","08","Delhi (North West)","Delhi"],
  ["DL","09","Delhi (North East)","Delhi"],
  ["DL","10","Delhi (New Delhi)","Delhi"],
  ["DL","11","Delhi (Rohini)","Delhi"],
  ["DL","12","Delhi (Dwarka)","Delhi"],
  ["LD","01","Kavaratti","Lakshadweep"],
  ["PY","01","Puducherry","Puducherry"],
  ["PY","02","Karaikal","Puducherry"],
  ["PY","03","Mahe","Puducherry"],
  ["PY","04","Yanam","Puducherry"],
];

function pad(n: string): string {
  return n.padStart(2, "0");
}

const records: RTORecord[] = RTO_RAW.map(([stateCode, num, name, state]) => {
  const number = pad(num);
  const code = `${stateCode}-${number}`;
  return {
    code,
    stateCode,
    number,
    name,
    state,
    stateSlug: slugify(state),
    city: name.replace(/\s*\(.*?\)\s*/g, "").trim(),
    slug: slugify(code),
  };
});

// Build per-state index
const byState: Record<string, RTORecord[]> = {};
for (const r of records) {
  if (!byState[r.stateSlug]) byState[r.stateSlug] = [];
  byState[r.stateSlug].push(r);
}

const OUT_DIR = path.join(process.cwd(), "data", "rto");
fs.mkdirSync(OUT_DIR, { recursive: true });

fs.writeFileSync(path.join(OUT_DIR, "rto.json"), JSON.stringify(records, null, 0));
fs.writeFileSync(path.join(OUT_DIR, "by-state.json"), JSON.stringify(byState, null, 0));

// Index: code → record
const index: Record<string, RTORecord> = {};
for (const r of records) index[r.code] = r;
fs.writeFileSync(path.join(OUT_DIR, "index.json"), JSON.stringify(index, null, 0));

console.log(`✅ Generated ${records.length} RTO records across ${Object.keys(byState).length} states`);
console.log(`📁 Output: ${OUT_DIR}`);
