#!/usr/bin/env node
/**
 * Hand-written original rewrites of high-traffic scheme prose, to de-dupe from
 * myScheme's verbatim text. Every fact/number/step preserved; wording is ours.
 * Reads raw _detail/<msSlug>.json for metadata + references, overrides the prose
 * fields, writes _detail_rw/<msSlug>.json. Reversible: delete the _rw file.
 *
 * Append new batches to REWRITES over time; re-running is idempotent.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RAW = path.join(ROOT, "data", "schemes", "_detail");
const OUT = path.join(ROOT, "data", "schemes", "_detail_rw");

const REWRITES = {
  "pm-kisan": {
    briefDescription: "PM-KISAN is a central government scheme that pays eligible land-owning farmer families ₹6,000 a year, in three instalments, directly to their bank accounts.",
    descriptionMd: "PM-KISAN is a central-sector income-support scheme run by the Department of Agriculture & Farmers Welfare. It gives every eligible land-owning farmer family a fixed yearly cash benefit to help meet the cost of seeds, fertiliser and other farming inputs. The money is paid straight into the farmer's bank account through Direct Benefit Transfer (DBT), so the full amount reaches the beneficiary with no middlemen and no deductions.",
    benefitsMd: "- **₹6,000 every year**, released in **three equal instalments of ₹2,000**, roughly once every four months.\n- Paid directly to your bank account by **Direct Benefit Transfer (DBT)** — no agents, no cuts.\n- Meant to ease the cost of crop inputs and routine family needs across the farming cycle.",
    eligibilityMd: "You qualify if your family **owns cultivable agricultural land recorded in your name**. Here a 'family' means the husband, wife and their minor children, and the benefit is paid **per family** rather than per individual landholder.",
    exclusionsMd: "Several higher-income groups are excluded even if they own farmland. You are **not** eligible if you — or any member of your family — fall under any of the following:\n\n- Institutional land holders.\n- Current or former holders of constitutional posts.\n- Current or former Ministers, MPs, MLAs, MLCs, Mayors of Municipal Corporations, or Chairpersons of District Panchayats.\n- Serving or retired officers and employees of central/state government departments, PSUs and government bodies — **except** Group D / Class IV / Multi-Tasking Staff.\n- Retired pensioners drawing a monthly pension of **₹10,000 or more** (again excluding Group D / Class IV / MTS).\n- Anyone who **paid income tax** in the last assessment year.\n- Practising professionals registered with their professional bodies — doctors, engineers, lawyers, chartered accountants and architects.",
    applicationMd: "You can register yourself online in a few minutes:\n\n**Step 1:** Go to the official PM-KISAN portal at [pmkisan.gov.in](https://pmkisan.gov.in/).\n**Step 2:** Open **'New Farmer Registration'**.\n**Step 3:** Enter your **Aadhaar number** and **mobile number**.\n**Step 4:** Verify the **OTP** to authenticate your Aadhaar with UIDAI.\n**Step 5:** Fill in your land and bank details and upload the required documents.\n**Step 6:** Submit the form.\n\nAfter registering, you can check your payments any time using the **'Know Your Status'** tool on the same portal.",
  },

  "pmmy": {
    briefDescription: "Pradhan Mantri Mudra Yojana (PMMY) offers collateral-free loans of up to ₹20 lakh to small, non-farm businesses through banks, NBFCs and microfinance institutions.",
    descriptionMd: "Pradhan Mantri Mudra Yojana (PMMY) is a central scheme that helps small businesses get credit they would otherwise struggle to access. It funds income-generating micro enterprises in the non-farm sector — manufacturing, trading, services and activities allied to agriculture such as poultry, dairy and beekeeping — with loans of up to **₹20 lakh**.\n\nThe scheme is delivered through approved **Member Lending Institutions (MLIs)** rather than the government directly. These include:\n\n- Public sector banks\n- Private sector banks\n- State cooperative banks\n- Regional rural banks\n- Microfinance institutions (MFIs)\n- Non-Banking Finance Companies (NBFCs)\n- Small Finance Banks (SFBs)\n- Other financial intermediaries approved by MUDRA Ltd.\n\nInterest rates are set by each lender in line with RBI guidelines. Many banks **waive the processing fee on Shishu loans** (up to ₹50,000). Note that MUDRA does not appoint any agents or middlemen — be wary of anyone claiming to arrange a Mudra loan for a fee.",
    benefitsMd: "Loans are grouped into four stages based on how much funding the business needs:\n\n- **Shishu:** up to ₹50,000.\n- **Kishore:** above ₹50,000 and up to ₹5 lakh.\n- **Tarun:** above ₹5 lakh and up to ₹10 lakh.\n- **Tarun Plus:** up to ₹20 lakh, for entrepreneurs who have already repaid a loan under the Tarun category.",
    eligibilityMd: "The following can apply for a Mudra loan:\n\n- Individuals\n- Proprietorship concerns\n- Partnership firms\n- Private limited companies\n- Public companies\n- Other legal business forms\n\nA few conditions apply: you should **not be a defaulter** with any bank or financial institution and should have a satisfactory credit record. Individual borrowers may need the relevant skills or experience for the activity, and any educational-qualification requirement depends on the nature of the proposed business.",
    applicationMd: "Keep these ready before you start: ID proof, address proof, a passport-size photo, your signature, and proof of identity/address of the business.\n\n**Step 1:** Visit the PM MUDRA site at [mudra.org.in](https://www.mudra.org.in), then go to the [Udyamimitra portal](https://udyamimitra.in/).\n**Step 2:** Click **'Apply Now'** for a Mudra loan.\n**Step 3:** Choose your category — new entrepreneur, existing entrepreneur, or self-employed professional.\n**Step 4:** Enter your name, email and mobile number, and generate the OTP to register.\n\nAfter registering:\n\n**Step 5:** Fill in your personal and professional details.\n**Step 6:** Select a hand-holding agency if you need help preparing the proposal; otherwise go straight to the loan application.\n**Step 7:** Pick the loan category — Shishu, Kishore or Tarun.\n**Step 8:** Add your business information (name, activity, industry type) and financial details (ownership, existing and proposed credit, estimates, preferred lender).\n**Step 9:** Upload all required documents and submit. Note down the **application number** generated for future reference.",
  },

  "pmay-g": {
    briefDescription: "Pradhan Mantri Awaas Yojana – Gramin (PMAY-G) helps poor rural families build a permanent (pucca) house, with financial assistance of ₹1.2–1.3 lakh plus support for a toilet, LPG and labour.",
    descriptionMd: "Pradhan Mantri Awaas Yojana – Gramin (PMAY-G), launched in April 2016 by the Ministry of Rural Development, helps rural families without a proper home build a permanent **pucca house** with basic amenities. It targets households that are houseless or living in kutcha or dilapidated dwellings, as part of the wider 'Housing for All' goal.\n\nEach home must be at least **25 square metres**, including a dedicated space for clean cooking. Beneficiaries are identified from the Socio-Economic and Caste Census (SECC) data and verified by the Gram Sabha, and the assistance is transferred directly to the beneficiary's Aadhaar-linked bank or post-office account.",
    benefitsMd: "- **Construction assistance** of **₹1,20,000** per house in plain areas, and **₹1,30,000** in hilly states, difficult areas and IAP districts (Himalayan and North-Eastern states, and the UT of Jammu & Kashmir).\n- An optional **institutional loan of up to ₹70,000** at a 3% lower interest rate; subsidy can be claimed on a principal of up to ₹2,00,000.\n- A minimum house size of **25 sq m** with a dedicated hygienic cooking area.\n- **₹12,000** towards building a toilet, in convergence with Swachh Bharat Mission–Gramin.\n- Up to **95 days of unskilled wage employment** through MGNREGA.\n- A free **LPG connection** under Pradhan Mantri Ujjwala Yojana.\n- Convergence support for piped drinking water, electricity, clean cooking fuel and waste treatment.\n- All payments made electronically, straight to the beneficiary's account.",
    eligibilityMd: "The scheme covers **houseless families** and those living in **kutcha houses with zero, one or two rooms** (as per SECC data, subject to the exclusion checks below).\n\nSome groups are included automatically: households with no shelter, the destitute or those living on alms, manual scavengers, primitive tribal groups, and legally released bonded labourers.\n\nWithin eligible families, priority is decided by the degree of housing deprivation across categories (SC/ST, Minorities and Others) — houseless families come first, followed by those with fewer rooms.",
    exclusionsMd: "Eligibility is filtered in two stages.\n\n### Step 1 — Pucca houses removed\nHouseholds living in homes with pucca roofs and/or pucca walls, or with more than two rooms, are filtered out.\n\n### Step 2 — Automatic exclusion\nFrom the rest, a household is automatically excluded if it meets **any one** of these 13 conditions:\n\n1. Owns a motorised two/three/four-wheeler or a fishing boat.\n2. Owns mechanised three/four-wheeler agricultural equipment.\n3. Holds a Kisan Credit Card with a limit of ₹50,000 or more.\n4. Has a family member who is a government employee.\n5. Runs a non-agricultural enterprise registered with the government.\n6. Has any member earning more than ₹10,000 a month.\n7. Pays income tax.\n8. Pays professional tax.\n9. Owns a refrigerator.\n10. Owns a landline phone.\n11. Owns 2.5 acres or more of irrigated land with at least one irrigation device.\n12. Owns 5 acres or more of irrigated land for two or more crop seasons.\n13. Owns 7.5 acres of land or more with at least one irrigation device.",
    applicationMd: "Registration has four parts — personal details, bank account details, convergence details, and details filled in by the concerned office.\n\n**Step 1:** Log in to the official PMAY-G portal.\n**Step 2:** Fill in the personal details (gender, mobile number, Aadhaar number, etc.).\n**Step 3:** Upload the consent form for using the Aadhaar number.\n**Step 4:** Search for the beneficiary to view the name, PMAY ID and priority.\n**Step 5:** Click **'Select to Register'** — the beneficiary details are generated automatically.\n**Step 6:** Complete the remaining details such as ownership type, relation and Aadhaar number, and upload the consent form.\n**Step 7:** Add the bank account details (account holder name, account number, etc.) and submit.",
  },

  "ab-pmjay": {
    briefDescription: "Ayushman Bharat PM-JAY gives eligible poor and vulnerable families cashless health cover of up to ₹5 lakh per family per year at empanelled hospitals.",
    descriptionMd: "Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana (AB PM-JAY) is the world's largest health-assurance scheme, run by the Department of Health & Family Welfare. It provides eligible low-income families in both rural and urban areas with **cashless hospital cover of up to ₹5 lakh per family per year**, so that a medical emergency does not push a family into debt. Care is delivered at empanelled public and private hospitals across the country.",
    benefitsMd: "- **Cashless cover of up to ₹5,00,000 per family per year** for hospitalisation.\n- Covers the full treatment chain — consultation, medicines, diagnostics, surgery, ICU, implants, room and food.\n- Includes **3 days of pre-hospitalisation** and **15 days of post-hospitalisation** expenses.\n- Covers complications that arise during treatment.\n- **Pre-existing conditions are covered from day one.**\n- **No cap on family size, age or gender** — every eligible member is covered.",
    eligibilityMd: "Eligibility is based on the deprivation and occupational categories of the SECC database, so there is **no enrolment fee or age limit**.\n\nIn **rural areas**, families qualify if they fall under the SECC deprivation criteria, along with automatic inclusion for the most vulnerable — the destitute or those surviving on alms, manual scavenger households, primitive tribal groups, and legally released bonded labourers. Eligible **urban** households are identified through their occupational category. You can check your eligibility on the PM-JAY portal or at any empanelled hospital.",
    applicationMd: "There is no separate online application — identification is done with help from an **Arogya Mitra** at any empanelled hospital or Common Service Centre (CSC):\n\n**Step 1:** Submit your PM letter / RSBY URN / ration card number / mobile number. The operator searches the beneficiary list using these details.\n**Step 2:** The operator searches the BIS application against the SECC, RSBY and state health-scheme databases.\n**Step 3:** **Individual identification** — your Aadhaar or government ID and ration card (or family ID) are verified and scanned.\n**Step 4:** **Family identification** — family records are confirmed through the ration card, and the documents are uploaded and submitted for approval.\n**Step 5:** The trust or insurance company **approves or recommends rejection**; rejections are finally decided by the State Health Agency (SHA).\n**Step 6:** Once approved, your **e-card is issued** and you can avail cashless treatment.",
  },

  "pm-svanidhi": {
    briefDescription: "PM SVANidhi gives street vendors collateral-free working-capital loans — starting at ₹15,000 and rising to ₹25,000 and ₹50,000 — with a 7% interest subsidy and cashback on digital payments.",
    descriptionMd: "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi) is a central scheme of the Ministry of Housing & Urban Affairs, launched on 1 June 2020 to help street vendors restart and grow their businesses. It offers **collateral-free working-capital loans**, an interest subsidy, and rewards for going digital, while helping bring vendors — hawkers, thelewalas, rehriwalas and other small sellers — into the formal economy.",
    benefitsMd: "### Working-capital loan\n- **1st loan:** up to **₹15,000**, repayable within 12 months.\n- **2nd loan:** up to **₹25,000**, repayable within 18 months.\n- **3rd loan:** up to **₹50,000**, repayable within 36 months.\n- Each higher loan unlocks on timely or early repayment of the previous one, and there is **no prepayment penalty**.\n\n### Interest subsidy\n- A **7% per year** interest subsidy on the loan, credited to your bank account every quarter.\n- Available only on standard (non-NPA) accounts, and valid up to **31 March 2033**.\n\n### Digital-transaction cashback\n- Earn cashback of **up to ₹100 a month** for accepting digital payments.\n\nThe scheme also comes with credit-guarantee support for the lending banks.",
    eligibilityMd: "The scheme is for street vendors who fall into any of these groups:\n\n- Vendors holding a **Certificate of Vending or Identity Card** issued by an Urban Local Body (ULB).\n- Vendors identified in the ULB survey but **not yet issued** a Certificate of Vending / ID Card.\n- Vendors left out of the survey, or who started vending after it, who hold a **Letter of Recommendation (LoR)** from the ULB or Town Vending Committee (TVC).\n- Vendors from surrounding peri-urban or rural areas who sell within the ULB's limits and hold an **LoR** from the ULB / TVC.",
    exclusionsMd: "",
    applicationMd: "**Step 1:** Go to the official portal at [pmsvanidhi.mohua.gov.in](https://pmsvanidhi.mohua.gov.in/) and click **'Log In'**.\n**Step 2:** Enter your **mobile number** and the captcha, then request an **OTP**.\n**Step 3:** After logging in, select your **vendor category** and enter your **Survey Reference Number (SRN)**, which is mandatory.\n**Step 4:** Complete the application form online, upload the required documents and submit.\n\nFor a detailed walkthrough, the portal also provides a step-by-step user manual.",
  },

  "apy": {
    briefDescription: "Atal Pension Yojana (APY) is a voluntary retirement scheme for savings-account holders aged 18–40 (who are not income-tax payers), giving a guaranteed monthly pension of ₹1,000–₹5,000 from age 60.",
    descriptionMd: "Atal Pension Yojana (APY) is an old-age income-security scheme aimed mainly at workers in the unorganised sector — the poor and under-privileged. It lets a savings-account holder aged **18 to 40** save a small amount each month during their working years in exchange for a **guaranteed monthly pension from the age of 60**. The exact pension depends on the amount you contribute and the age at which you join, as set out in the official APY contribution chart.",
    benefitsMd: "From the age of 60, an APY subscriber receives three guarantees:\n\n- **Guaranteed monthly pension:** a fixed pension of **₹1,000, ₹2,000, ₹3,000, ₹4,000 or ₹5,000 per month** (depending on your chosen plan), payable for life.\n- **Pension for the spouse:** after the subscriber's death, the spouse continues to receive the same monthly pension for life.\n- **Corpus for the nominee:** after both the subscriber and spouse have passed away, the accumulated pension corpus is returned to the nominee.",
    eligibilityMd: "- You must be **between 18 and 40 years old** to join, and you start receiving the pension at **age 60**.\n- You need a **savings bank account**; contributions are collected by **auto-debit** on a monthly, quarterly or half-yearly basis and continue until you turn 60.\n- **From 1 October 2022, anyone who is or has been an income-tax payer is not eligible** to join APY.",
    exclusionsMd: "Since **1 October 2022**, any citizen who is, or has previously been, an income-tax payer cannot join APY.",
    applicationMd: "You can enrol online in one of two ways.\n\n### Through your bank's net banking\n**Step 1:** Log in to your internet-banking account and search for **APY** on the dashboard.\n**Step 2:** Fill in your basic and nominee details.\n**Step 3:** Give consent for the monthly contribution to be auto-debited, and submit the form.\n\n### Through the eNPS portal\n**Step 1:** Visit the eNPS website ([enps.nsdl.com](https://enps.nsdl.com/eNPS/NationalPensionSystem.html)) and select **'Atal Pension Yojana'**, then **'APY Registration'**.\n**Step 2:** Fill in your basic details and complete KYC — for example, by verifying your **Aadhaar**.\n**Step 3:** Add nominee details, authorise the auto-debit and submit.",
  },

  "pmjjby": {
    briefDescription: "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY) is a renewable one-year life-insurance cover of ₹2 lakh for bank/post-office account holders aged 18–50, for a premium of ₹436 a year.",
    descriptionMd: "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY) is a low-cost life-insurance scheme that pays out on death due to **any cause**. It is a one-year term cover that renews every year, offered through participating banks and post offices and backed by life-insurance companies. Any account holder of a participating bank or post office aged **18 to 50** can join.",
    benefitsMd: "- **Life cover of ₹2 lakh** for one year, payable to your nominee on death due to **any reason**.\n- The cover renews from year to year.\n- The premium is just **₹436 per year** per member, auto-debited from your bank or post-office account.",
    eligibilityMd: "- You must be **between 18 and 50 years old**.\n- You must hold an **individual bank or post-office account** and agree to the annual auto-debit of the premium.",
    exclusionsMd: "",
    applicationMd: "PMJJBY is enrolled offline through your bank or post office:\n\n**Step 1:** Download and print the **Consent-cum-Declaration form** from the official Jansuraksha portal.\n**Step 2:** Fill in and sign the form, attach self-attested copies of the required documents, and submit it to the authorised official at your bank or post office.\n**Step 3:** The official will hand you the **Acknowledgement Slip Cum Certificate of Insurance** as proof of cover.",
  },

  "pmsby": {
    briefDescription: "Pradhan Mantri Suraksha Bima Yojana (PMSBY) is an accident-insurance cover of up to ₹2 lakh for bank account holders aged 18–70, for a premium of just ₹20 a year.",
    descriptionMd: "Pradhan Mantri Suraksha Bima Yojana (PMSBY) is an affordable accident-insurance scheme covering **accidental death and disability**. For a premium of just **₹20 a year**, auto-debited from your bank or post-office account on or before 1 June each year, you get one year of cover running from **1 June to 31 May**.",
    benefitsMd: "The cover pays out as follows:\n\n- **Accidental death:** ₹2 lakh to the nominee.\n- **Total and permanent disability** — loss of both eyes, both hands or feet, or sight of one eye plus loss of a hand or foot: **₹2 lakh**.\n- **Partial permanent disability** — loss of sight of one eye, or loss of use of one hand or foot: **₹1 lakh**.",
    eligibilityMd: "- Individual **bank account holders aged 18 to 70** of participating banks can join by giving consent and enabling the annual auto-debit.\n- The cover ends when the member turns **70**, or if the bank account is closed.",
    exclusionsMd: "",
    applicationMd: "PMSBY is enrolled offline:\n\n**Step 1:** Visit the bank branch where you hold a savings account, or download the form from the official Jansuraksha portal ([jansuraksha.gov.in](https://jansuraksha.gov.in/Forms-PMSBY.aspx)).\n**Step 2:** Fill in the form and submit it to the bank along with the required documents.\n**Step 3:** Once enrolled, you receive an **Acknowledgement Slip Cum Certificate of Insurance**.",
  },

  "pmuy": {
    briefDescription: "Pradhan Mantri Ujjwala Yojana (PMUY) gives women from poor households a free LPG connection, along with a free first refill and stove.",
    descriptionMd: "Pradhan Mantri Ujjwala Yojana (PMUY) is a scheme of the Ministry of Petroleum & Natural Gas that provides **deposit-free LPG connections to women from poor households** who do not already have one. By replacing firewood, coal and cow-dung cakes with clean cooking gas, it protects the health of rural women and reduces household pollution. Under Ujjwala 2.0, priority goes to states whose LPG coverage was below the national average as on 1 January 2016.",
    benefitsMd: "- A **deposit-free LPG connection** worth **₹1,600** for a 14.2 kg cylinder, or **₹1,150** for a 5 kg cylinder.\n- Every beneficiary also gets a **free first refill** and a **free stove (hot plate)** along with the connection.",
    eligibilityMd: "The applicant must be an **adult woman from a poor household that does not already have an LPG connection**, falling into any of these categories:\n\n- Listed in the **SECC 2011** data.\n- Belonging to **SC/ST households**, or a beneficiary of PMAY (Gramin), Antyodaya Anna Yojana (AAY); forest dwellers, Most Backward Classes (MBC), tea and ex-tea garden tribes, or people living on river islands (with supporting documents).\n- If none of the above applies, she can still claim eligibility as a **poor household** by submitting the 14-point declaration.",
    exclusionsMd: "A male member of a household cannot apply for the connection — the scheme is in the woman's name.",
    applicationMd: "Before you start, keep ready your **Aadhaar card, ration card, address proof, a passport-size photo and bank details**.\n\n**Step 1:** Apply online on the official portal ([pmuy.gov.in](https://www.pmuy.gov.in)).\n**Step 2:** Choose the gas company — Indane, Bharatgas or HP Gas.\n**Step 3:** Select the connection type, e.g. **Ujjwala 2.0 New Connection**, and choose your state, district and distributor.\n**Step 4:** Enter your mobile number, captcha and OTP, and indicate whether you are a migrant family.\n**Step 5:** Provide your family identifier — a ration card if you have one, or Annexure 1 if you do not — then select your category and complete the form.",
  },

  "pmjdy": {
    briefDescription: "Pradhan Mantri Jan Dhan Yojana (PMJDY) is India's financial-inclusion mission — a zero-balance bank account for every unbanked adult, with a free RuPay card carrying ₹2 lakh accident insurance and an overdraft of up to ₹10,000.",
    descriptionMd: "Pradhan Mantri Jan Dhan Yojana (PMJDY) is India's National Mission for Financial Inclusion, launched on 28 August 2014 to bring every unbanked adult into the formal banking system. It is built on four principles — banking the unbanked, securing the unsecured, funding the unfunded, and serving underserved areas. Since 2018 the focus shifted from 'every household' to 'every unbanked adult', and the account's benefits have been steadily enhanced.",
    benefitsMd: "- **Zero-balance account (BSBDA):** a Basic Savings Bank Deposit Account with **no minimum balance**. Deposit and withdraw at branches, ATMs and Banking Correspondents, with up to **4 withdrawals a month**.\n- **Small Account (Chota Khata):** open one **without legal documents** — valid 12 months, extendable by another 12 if you show you've applied for a valid ID.\n- **Free RuPay debit card with built-in accident insurance** of **₹2 lakh** (₹1 lakh for accounts opened before 28 August 2018).\n- **Overdraft of up to ₹10,000** for eligible account holders.\n- **Banking Correspondents / Bank Mitras** bring banking to rural areas far from a branch.",
    eligibilityMd: "- Any **Indian citizen** eligible to open a bank account can open a PMJDY account.\n- **Minors above 10 years** can open one with support from their legal guardian.",
    exclusionsMd: "",
    applicationMd: "PMJDY accounts are opened at a bank branch:\n\n**Step 1:** Go to the official portal ([pmjdy.gov.in](https://pmjdy.gov.in/)).\n**Step 2:** Under **'e-Documents'**, open the **Account Opening Form** (available in English and Hindi).\n**Step 3:** Download and print the form.\n**Step 4:** Fill in your bank, personal and address details (branch, town/village, block/district, Aadhaar, occupation, annual income, etc.).\n**Step 5:** Submit the form with the required documents at your nearest bank branch.",
  },

  "pmmvy": {
    briefDescription: "Pradhan Mantri Matru Vandana Yojana (PMMVY) gives maternity cash benefits to pregnant women and new mothers — ₹5,000 for the first child, and ₹6,000 for a second child if it is a girl.",
    descriptionMd: "Pradhan Mantri Matru Vandana Yojana (PMMVY) is a centrally sponsored scheme of the Ministry of Women & Child Development that supports pregnant women and lactating mothers from socially and economically disadvantaged groups. It provides maternity cash benefits for the first two living children (the second only if it is a girl), partly compensating wage loss and encouraging health checkups and institutional delivery.",
    benefitsMd: "### First child — ₹5,000 in two instalments\n- **₹3,000** on registering the pregnancy and attending **at least one antenatal checkup** within six months of the last menstrual period (at an Anganwadi Centre or approved health facility).\n- **₹2,000** once the **birth is registered** and the child has received all due vaccines up to **14 weeks** under the Universal Immunization Programme.\n\nThe mother is also entitled to the cash incentive under Janani Suraksha Yojana (JSY) after an institutional delivery.\n\n### Second child (only if a girl) — ₹6,000 in a single instalment\nPaid after pregnancy registration + one antenatal checkup, registration of the girl's birth, and all due vaccines up to 14 weeks.\n\nIn case of miscarriage or stillbirth, the woman is treated as a fresh beneficiary for any future pregnancy.",
    eligibilityMd: "- The applicant must be **at least 19 years old** and pregnant.\n- She should be **employed and facing wage loss** due to the pregnancy.\n- The benefit applies to the **first live birth** (and a second child only if it is a girl).\n- Apply **within 270 days of childbirth**.\n- Disadvantaged categories covered include women from SC/ST households and women with 40%+ disability, among others.",
    exclusionsMd: "- Women in **regular employment** with the Central/State Government or a PSU, or already receiving similar maternity benefits under any other law, are **not** eligible.\n- The husband's Aadhaar is **not** mandatory to claim the benefit.",
    applicationMd: "Apply online on the PMMVY portal:\n\n**Step 1:** Visit [pmmvy.wcd.gov.in](https://pmmvy.wcd.gov.in/) and open **'Citizen Login'**.\n**Step 2:** Enter and verify your mobile number, then fill in your name, state, district, area, block, village and relationship to the beneficiary, and create your account.\n**Step 3:** Log in with your User ID, password and captcha.\n**Step 4:** Open the **'Data Entry'** tab and choose **'Beneficiary Registration'**.\n**Step 5:** Fill in the beneficiary details and select whether you are applying for the first or second child, then submit.",
  },

  "sui": {
    briefDescription: "Stand-Up India facilitates bank loans of ₹10 lakh to ₹1 crore for SC/ST and women entrepreneurs to set up a new (greenfield) business in manufacturing, services, trading or activities allied to agriculture.",
    descriptionMd: "Stand-Up India, run by the Department of Financial Services (Ministry of Finance), helps **Scheduled Caste / Scheduled Tribe and women entrepreneurs** access bank finance to start a new business. Every bank branch is expected to fund at least one SC/ST borrower and one woman borrower for a **greenfield** (first-time) enterprise in manufacturing, services, trading, or activities allied to agriculture. For a company or firm, at least **51% of the shareholding and control** must be held by an SC/ST or woman entrepreneur.",
    benefitsMd: "- A **composite loan** (term loan + working capital) of **₹10 lakh to ₹1 crore**.\n- A **RuPay debit card** issued for the borrower's convenience.\n- **Hand-holding support** through the SIDBI Stand-Up Mitra portal — training, skilling, mentoring, project-report preparation, application help, work-shed/utility support and links to subsidy schemes.",
    eligibilityMd: "- The loan is for a **greenfield (brand-new) enterprise** only.\n- A **male** applicant must belong to the **SC/ST** category; women of any category are eligible.\n- The applicant must be **at least 18 years old**.\n- The applicant must **not be in default** to any bank or financial institution.",
    exclusionsMd: "",
    applicationMd: "You can apply three ways — at a bank branch, through your district's Lead District Manager (LDM), or online:\n\n**Step 1:** Go to the Stand-Up Mitra portal ([standupmitra.in](https://www.standupmitra.in/Login/Register)) and register.\n**Step 2:** Enter your business location details.\n**Step 3:** Select your category (SC, ST or Woman) and confirm the 51% stake condition for non-individual enterprises.\n**Step 4:** Complete the application; the portal connects you to the lending bank and hand-holding agencies.\n\nAlternatively, visit your nearest bank branch or contact your district LDM to apply offline.",
  },

  "kccp": {
    briefDescription: "Kisan Credit Card (Pashupalan) is a Madhya Pradesh scheme giving livestock farmers short-term working-capital loans at subsidised interest for dairy and animal-husbandry activities.",
    descriptionMd: "The Kisan Credit Card (Pashupalan) scheme, run by the Animal Husbandry & Dairy Department of Madhya Pradesh, provides **short-term working-capital loans** to livestock farmers at subsidised interest rates. Eligible livestock farmers, dairy producers and members of primary agricultural credit cooperative societies can access funds for day-to-day operational needs through banks, on the Kisan Credit Card system.",
    benefitsMd: "- A **short-term working-capital loan** for livestock and dairy activities, via the Kisan Credit Card.\n- An **interest subsidy** on the sanctioned loan.\n- Loans are typically **disbursed within about 15 days** of approval.",
    eligibilityMd: "- The applicant must be a **resident of Madhya Pradesh**.\n- They must be a **livestock farmer** or a member of a **primary agricultural credit cooperative society**.\n- They must need short-term working capital for livestock activities, including dairy production.",
    exclusionsMd: "",
    applicationMd: "Apply online through the MP SAMAST portal:\n\n**Step 1:** Go to [samast.mponline.gov.in](https://samast.mponline.gov.in/portal/) and click **'Create Profile'**.\n**Step 2:** Fill in your basic details — name, mobile number, gender, email and date of birth — and continue.\n**Step 3:** Re-enter your date of birth and mobile number, enter the captcha, and verify with the OTP sent to your mobile.\n**Step 4:** Complete **Aadhaar e-KYC** using your Aadhaar number, registered mobile and OTP, then proceed with the loan application.",
  },
};

let done = 0;
for (const [k, ov] of Object.entries(REWRITES)) {
  const rawFile = path.join(RAW, `${k}.json`);
  if (!fs.existsSync(rawFile)) { console.error(`  ✗ no raw detail for ${k}`); continue; }
  const base = JSON.parse(fs.readFileSync(rawFile, "utf8"));
  const merged = { ...base, ...ov, rewritten: true, fetchedAt: base.fetchedAt };
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, `${k}.json`), JSON.stringify(merged, null, 2));
  done++;
  console.log(`  ✓ ${k}`);
}
console.log(`Rewrote ${done} schemes → _detail_rw/`);
