#!/usr/bin/env node
/**
 * Hand-written original rewrites of the highest-traffic scheme prose, to de-dupe
 * from myScheme's verbatim text (Google scaled-content risk). Keeps every fact;
 * only the wording/structure is ours. Reads the raw _detail/<msSlug>.json for
 * metadata + references, overrides the prose fields, writes _detail_rw/<msSlug>.json.
 * Reversible: delete the _rw file to fall back to raw myScheme content.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RAW = path.join(ROOT, "data", "schemes", "_detail");
const OUT = path.join(ROOT, "data", "schemes", "_detail_rw");

const REWRITES = {
  "pm-kisan": {
    briefDescription: "PM-KISAN is a central government scheme that pays eligible land-owning farmer families ₹6,000 a year, in three instalments, directly to their bank accounts.",
    descriptionMd: "PM-KISAN is a central-sector income-support scheme run by the Department of Agriculture & Farmers Welfare. It gives every eligible land-owning farmer family a fixed yearly cash benefit to help meet the cost of seeds, fertiliser and other farming inputs. The money is paid straight into the farmer's bank account through Direct Benefit Transfer (DBT), so the full amount reaches the beneficiary with no middlemen and no deductions.",
    benefitsMd: "- **₹6,000 every year**, released in **three equal instalments of ₹2,000**, roughly once every four months.\n- Paid directly to your bank account by **Direct Benefit Transfer (DBT)** — no agents, no cuts.\n- Meant to ease the cost of crop inputs and routine family needs across the farming cycle.",
    eligibilityMd: "You qualify if your family **owns cultivable agricultural land recorded in your name**. Here a 'family' means the husband, wife and their minor children, and the benefit is paid **per family** rather than per individual landholder.",
    exclusionsMd: "Several higher-income groups are excluded even if they own farmland. You are **not** eligible if you — or any member of your family — fall under any of the following:\n\n- Institutional land holders.\n- Current or former holders of constitutional posts.\n- Current or former Ministers, MPs, MLAs, MLCs, Mayors of Municipal Corporations, or Chairpersons of District Panchayats.\n- Serving or retired officers and employees of central/state government departments, PSUs and government bodies — **except** Group D / Class IV / Multi-Tasking Staff.\n- Retired pensioners drawing a monthly pension of **₹10,000 or more** (again excluding Group D / Class IV / MTS).\n- Anyone who **paid income tax** in the last assessment year.\n- Practising professionals registered with their professional bodies — doctors, engineers, lawyers, chartered accountants and architects.",
    applicationMd: "You can register yourself online in a few minutes:\n\n**Step 1:** Go to the official PM-KISAN portal at [pmkisan.gov.in](https://pmkisan.gov.in/).\n**Step 2:** Open **'New Farmer Registration'**.\n**Step 3:** Enter your **Aadhaar number** and **mobile number**.\n**Step 4:** Verify the **OTP** to authenticate your Aadhaar with UIDAI.\n**Step 5:** Fill in your land and bank details and upload the required documents.\n**Step 6:** Submit the form.\n\nAfter registering, you can check your payments any time using the **'Know Your Status'** tool on the same portal.",
  },

  "pmmy": {
    briefDescription: "Pradhan Mantri Mudra Yojana (PMMY) offers collateral-free loans of up to ₹20 lakh to small, non-farm businesses through banks, NBFCs and microfinance institutions.",
    descriptionMd: "Pradhan Mantri Mudra Yojana (PMMY) is a central scheme that helps small businesses get credit they would otherwise struggle to access. It funds income-generating micro enterprises in the non-farm sector — manufacturing, trading, services and activities allied to agriculture such as poultry, dairy and beekeeping — with loans of up to **₹20 lakh**.\n\nThe scheme is delivered through approved **Member Lending Institutions (MLIs)** rather than the government directly. These include:\n\n- Public sector banks\n- Private sector banks\n- State cooperative banks\n- Regional rural banks\n- Microfinance institutions (MFIs)\n- Non-Banking Finance Companies (NBFCs)\n- Small Finance Banks (SFBs)\n- Other financial intermediaries approved by MUDRA Ltd.\n\nInterest rates are set by each lender in line with RBI guidelines. Many banks **waive the processing fee on Shishu loans** (up to ₹50,000). Note that MUDRA does not appoint any agents or middlemen — be wary of anyone claiming to arrange a Mudra loan for a fee.",
    benefitsMd: "Loans are grouped into four stages based on how much funding the business needs:\n\n- **Shishu:** up to ₹50,000.\n- **Kishore:** above ₹50,000 and up to ₹5 lakh.\n- **Tarun:** above ₹5 lakh and up to ₹10 lakh.\n- **Tarun Plus:** up to ₹20 lakh, for entrepreneurs who have already repaid a loan under the Tarun category.",
    eligibilityMd: "The following can apply for a Mudra loan:\n\n- Individuals\n- Proprietorship concerns\n- Partnership firms\n- Private limited companies\n- Public companies\n- Other legal business forms\n\nA few conditions apply: you should **not be a defaulter** with any bank or financial institution and should have a satisfactory credit record. Individual borrowers may need the relevant skills or experience for the activity, and any educational-qualification requirement depends on the nature of the proposed business.",
    applicationMd: "Keep these ready before you start: ID proof, address proof, a passport-size photo, your signature, and proof of identity/address of the business.\n\n**Step 1:** Visit the PM MUDRA site at [mudra.org.in](https://www.mudra.org.in), then go to the [Udyamimitra portal](https://udyamimitra.in/).\n**Step 2:** Click **'Apply Now'** for a Mudra loan.\n**Step 3:** Choose your category — new entrepreneur, existing entrepreneur, or self-employed professional.\n**Step 4:** Enter your name, email and mobile number, and generate the OTP to register.\n\nAfter registering:\n\n**Step 5:** Fill in your personal and professional details.\n**Step 6:** Select a hand-holding agency if you need help preparing the proposal; otherwise go straight to the loan application.\n**Step 7:** Pick the loan category — Shishu, Kishore or Tarun.\n**Step 8:** Add your business information (name, activity, industry type) and financial details (ownership, existing and proposed credit, estimates, preferred lender).\n**Step 9:** Upload all required documents and submit. Note down the **application number** generated for future reference.",
  },

  "pmay-g": {
    briefDescription: "Pradhan Mantri Awaas Yojana – Gramin (PMAY-G) helps poor rural families build a permanent (pucca) house, with financial assistance of ₹1.2–1.3 lakh plus support for a toilet, LPG and labour.",
    descriptionMd: "Pradhan Mantri Awaas Yojana – Gramin (PMAY-G), launched in April 2016 by the Ministry of Rural Development, helps rural families without a proper home build a permanent **pucca house** with basic amenities. It targets households that are houseless or living in kutcha or dilapidated dwellings, as part of the wider 'Housing for All' goal.\n\nEach home must be at least **25 square metres**, including a dedicated space for clean cooking. Beneficiaries are identified from the Socio-Economic and Caste Census (SECC) data and verified by the Gram Sabha, and the assistance is transferred directly to the beneficiary's Aadhaar-linked bank or post-office account.",
    benefitsMd: "- **Construction assistance** of **₹1,20,000** per house in plain areas, and **₹1,30,000** in hilly states, difficult areas and IAP districts (Himalayan and North-Eastern states, and the UT of Jammu & Kashmir).\n- An optional **institutional loan of up to ₹70,000** at a 3% lower interest rate; subsidy can be claimed on a principal of up to ₹2,00,000.\n- A minimum house size of **25 sq m** with a dedicated hygienic cooking area.\n- **₹12,000** towards building a toilet, in convergence with Swachh Bharat Mission–Gramin.\n- Up to **95 days of unskilled wage employment** through MGNREGA.\n- A free **LPG connection** under Pradhan Mantri Ujjwala Yojana.\n- Convergence support for piped drinking water, electricity, clean cooking fuel and waste treatment.\n- All payments made electronically, straight to the beneficiary's account.",
    eligibilityMd: "The scheme covers **houseless families** and those living in **kutcha houses with zero, one or two rooms** (as per SECC data, subject to the exclusion checks below).\n\nSome groups are included automatically: households with no shelter, the destitute or those living on alms, manual scavengers, primitive tribal groups, and legally released bonded labourers.\n\nWithin eligible families, priority is decided by the degree of housing deprivation across categories (SC/ST, Minorities and Others) — houseless families come first, followed by those with fewer rooms.",
    exclusionsMd: "Eligibility is filtered in two stages.\n\n### Step 1 — Pucca houses removed\nHouseholds living in homes with pucca roofs and/or pucca walls, or with more than two rooms, are filtered out.\n\n### Step 2 — Automatic exclusion\nFrom the rest, a household is automatically excluded if it meets **any one** of these 13 conditions:\n\n1. Owns a motorised two/three/four-wheeler or a fishing boat.\n2. Owns mechanised three/four-wheeler agricultural equipment.\n3. Holds a Kisan Credit Card with a limit of ₹50,000 or more.\n4. Has a family member who is a government employee.\n5. Runs a non-agricultural enterprise registered with the government.\n6. Has any member earning more than ₹10,000 a month.\n7. Pays income tax.\n8. Pays professional tax.\n9. Owns a refrigerator.\n10. Owns a landline phone.\n11. Owns 2.5 acres or more of irrigated land with at least one irrigation device.\n12. Owns 5 acres or more of irrigated land for two or more crop seasons.\n13. Owns 7.5 acres of land or more with at least one irrigation device.",
    applicationMd: "Registration has four parts — personal details, bank account details, convergence details, and details filled in by the concerned office.\n\n**Step 1:** Log in to the official PMAY-G portal.\n**Step 2:** Fill in the personal details (gender, mobile number, Aadhaar number, etc.).\n**Step 3:** Upload the consent form for using the Aadhaar number.\n**Step 4:** Search for the beneficiary to view the name, PMAY ID and priority.\n**Step 5:** Click **'Select to Register'** — the beneficiary details are generated automatically.\n**Step 6:** Complete the remaining details such as ownership type, relation and Aadhaar number, and upload the consent form.\n**Step 7:** Add the bank account details (account holder name, account number, etc.) and submit.",
  },

  "ab-pmjay": {
    briefDescription: "Ayushman Bharat PM-JAY gives eligible poor and vulnerable families cashless health cover of up to ₹5 lakh per family per year at empanelled hospitals.",
    descriptionMd: "Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana (AB PM-JAY) is the world's largest health-assurance scheme, run by the Department of Health & Family Welfare. It provides eligible low-income families in both rural and urban areas with **cashless hospital cover of up to ₹5 lakh per family per year**, so that a medical emergency does not push a family into debt. Care is delivered at empanelled public and private hospitals across the country.",
    benefitsMd: "- **Cashless cover of up to ₹5,00,000 per family per year** for hospitalisation.\n- Covers the full treatment chain — consultation, medicines, diagnostics, surgery, ICU, implants, room and food.\n- Includes **3 days of pre-hospitalisation** and **15 days of post-hospitalisation** expenses.\n- Covers complications that arise during treatment.\n- **Pre-existing conditions are covered from day one.**\n- **No cap on family size, age or gender** — every eligible member is covered.",
    eligibilityMd: "Eligibility is based on the deprivation and occupational categories of the SECC database, so there is **no enrolment fee or age limit**.\n\nIn **rural areas**, families qualify if they fall under the SECC deprivation criteria, along with automatic inclusion for the most vulnerable — the destitute or those surviving on alms, manual scavenger households, primitive tribal groups, and legally released bonded labourers. Eligible **urban** households are identified through their occupational category. You can check your eligibility on the PM-JAY portal or at any empanelled hospital.",
    applicationMd: "There is no separate online application — identification is done with help from an **Arogya Mitra** at any empanelled hospital or Common Service Centre (CSC):\n\n**Step 1:** Submit your PM letter / RSBY URN / ration card number / mobile number. The operator searches the beneficiary list using these details.\n**Step 2:** The operator searches the BIS application against the SECC, RSBY and state health-scheme databases.\n**Step 3:** **Individual identification** — your Aadhaar or government ID and ration card (or family ID) are verified and scanned.\n**Step 4:** **Family identification** — family records are confirmed through the ration card, and the documents are uploaded and submitted for approval.\n**Step 5:** The trust or insurance company **approves or recommends rejection**; rejections are finally decided by the State Health Agency (SHA).\n**Step 6:** Once approved, your **e-card is issued** and you can avail cashless treatment.",
  },
};

let done = 0;
for (const [k, ov] of Object.entries(REWRITES)) {
  const rawFile = path.join(RAW, `${k}.json`);
  if (!fs.existsSync(rawFile)) { console.error(`  ✗ no raw detail for ${k}`); continue; }
  const base = JSON.parse(fs.readFileSync(rawFile, "utf8"));
  const merged = { ...base, ...ov, rewritten: true, fetchedAt: base.fetchedAt };
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, `${k}.json`), JSON.stringify(merged, null, 2));
  done++;
  console.log(`  ✓ ${k}`);
}
console.log(`Rewrote ${done} schemes → _detail_rw/`);
